//! Module manifest format (`manifest.toml`).
//!
//! Every module in the cache or vendor layer ships a `manifest.toml` that
//! describes its identity, version, and exported functions. Generated by
//! `duumbi init` for stdlib modules and by `duumbi deps vendor` for vendored
//! dependencies.

#![allow(dead_code)] // Progressively integrated as the module resolution pipeline is built

use std::fs;
use std::path::Path;

use serde::{Deserialize, Serialize};
use thiserror::Error;

// ---------------------------------------------------------------------------
// Error type
// ---------------------------------------------------------------------------

/// Errors produced when reading or writing a `manifest.toml`.
#[derive(Debug, Error)]
pub enum ManifestError {
    /// The manifest file could not be read.
    #[error("Failed to read manifest at '{path}': {source}")]
    Io {
        /// File path that failed.
        path: String,
        /// Underlying I/O error.
        #[source]
        source: std::io::Error,
    },

    /// The manifest TOML is malformed.
    #[error("Failed to parse manifest at '{path}': {source}")]
    Parse {
        /// File path that failed.
        path: String,
        /// Underlying parse error.
        #[source]
        source: toml::de::Error,
    },
}

// ---------------------------------------------------------------------------
// Manifest types
// ---------------------------------------------------------------------------

/// The `[module]` section of a `manifest.toml`.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
pub struct ModuleInfo {
    /// Scoped module name, e.g. `"@duumbi/stdlib-math"`.
    pub name: String,
    /// Semantic version string, e.g. `"1.0.0"`.
    pub version: String,
    /// Human-readable description.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub description: String,
    /// SPDX license identifier.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub license: String,
}

/// The `[exports]` section of a `manifest.toml`.
#[derive(Debug, Clone, Default, PartialEq, Eq, Deserialize, Serialize)]
pub struct ExportsInfo {
    /// Names of all exported functions.
    #[serde(default)]
    pub functions: Vec<String>,
}

/// Parsed contents of a module `manifest.toml`.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
pub struct ModuleManifest {
    /// Core module metadata.
    pub module: ModuleInfo,
    /// Exported symbols declared by this module.
    #[serde(default)]
    pub exports: ExportsInfo,
}

impl ModuleManifest {
    /// Constructs a manifest for a stdlib module.
    pub fn new(
        name: impl Into<String>,
        version: impl Into<String>,
        description: impl Into<String>,
        exports: Vec<String>,
    ) -> Self {
        Self {
            module: ModuleInfo {
                name: name.into(),
                version: version.into(),
                description: description.into(),
                license: "MPL-2.0".to_string(),
            },
            exports: ExportsInfo { functions: exports },
        }
    }

    /// Renders this manifest as a TOML string suitable for writing to disk.
    #[must_use]
    pub fn to_toml(&self) -> String {
        toml::to_string_pretty(self).unwrap_or_default()
    }
}

// ---------------------------------------------------------------------------
// I/O helpers
// ---------------------------------------------------------------------------

/// Parses a `manifest.toml` from the given file path.
///
/// Returns `Err` if the file cannot be read or is not valid TOML that matches
/// the expected manifest shape.
#[must_use = "manifest parse errors should be handled"]
pub fn parse_manifest(path: &Path) -> Result<ModuleManifest, ManifestError> {
    let contents = fs::read_to_string(path).map_err(|source| ManifestError::Io {
        path: path.display().to_string(),
        source,
    })?;
    toml::from_str(&contents).map_err(|source| ManifestError::Parse {
        path: path.display().to_string(),
        source,
    })
}

/// Writes a manifest to `<dir>/manifest.toml`.
///
/// Creates intermediate directories if necessary.
#[must_use = "manifest write errors should be handled"]
pub fn write_manifest(dir: &Path, manifest: &ModuleManifest) -> Result<(), ManifestError> {
    fs::create_dir_all(dir).map_err(|source| ManifestError::Io {
        path: dir.display().to_string(),
        source,
    })?;
    let path = dir.join("manifest.toml");
    fs::write(&path, manifest.to_toml()).map_err(|source| ManifestError::Io {
        path: path.display().to_string(),
        source,
    })
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn sample() -> ModuleManifest {
        ModuleManifest::new(
            "@duumbi/stdlib-math",
            "1.0.0",
            "Mathematical utility functions (abs, max, min)",
            vec!["abs".into(), "max".into(), "min".into()],
        )
    }

    #[test]
    fn roundtrip_toml() {
        let m = sample();
        let toml_str = m.to_toml();
        let parsed: ModuleManifest = toml::from_str(&toml_str).expect("must parse roundtrip");
        assert_eq!(parsed, m);
    }

    #[test]
    fn parse_manifest_from_file() {
        let tmp = TempDir::new().expect("tempdir");
        let path = tmp.path().join("manifest.toml");
        fs::write(&path, sample().to_toml()).expect("write");
        let parsed = parse_manifest(&path).expect("must parse");
        assert_eq!(parsed, sample());
    }

    #[test]
    fn write_manifest_creates_file() {
        let tmp = TempDir::new().expect("tempdir");
        write_manifest(tmp.path(), &sample()).expect("must write");
        assert!(tmp.path().join("manifest.toml").exists());
        let parsed = parse_manifest(&tmp.path().join("manifest.toml")).expect("must parse");
        assert_eq!(parsed, sample());
    }

    #[test]
    fn parse_manifest_missing_file_returns_io_error() {
        let tmp = TempDir::new().expect("tempdir");
        let result = parse_manifest(&tmp.path().join("nonexistent.toml"));
        assert!(matches!(result, Err(ManifestError::Io { .. })));
    }

    #[test]
    fn parse_manifest_invalid_toml_returns_parse_error() {
        let tmp = TempDir::new().expect("tempdir");
        let path = tmp.path().join("bad.toml");
        fs::write(&path, "not valid toml [[[").expect("write");
        let result = parse_manifest(&path);
        assert!(matches!(result, Err(ManifestError::Parse { .. })));
    }

    #[test]
    fn exports_default_empty_when_section_absent() {
        let toml = "[module]\nname = \"@test/minimal\"\nversion = \"0.1.0\"\n";
        let parsed: ModuleManifest = toml::from_str(toml).expect("must parse");
        assert!(parsed.exports.functions.is_empty());
    }
}
