//! Creator construction: an Atlas-native design intent, its lowering to HTML/CSS, and its
//! verification against what the instrument observes on the rendered result (ADR 0017).
//!
//! The intent is ratio-first (ADR 0011): aspect ratios, flex shares, spacing in `em`, font
//! ratios, one structural breakpoint, and interaction/motion mechanisms (hover lift with an
//! easing and duration) -- the vocabulary the observation side extracts. Lowering emits neutral
//! placeholder content only; no reference text, brand or asset can reach the output.

use super::{
    InteractionAnalysis, InteractionMechanism, MotionInference, ResponsiveChange,
    VisualObservationReport,
};
use crate::ConstraintVerdict;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct HeroIntent {
    /// Media block aspect ratio `(width, height)`.
    pub media_aspect: (u32, u32),
    /// Flex share `(media, copy)` of the hero row above the breakpoint.
    pub share: (u32, u32),
    pub gap_em: f64,
    /// Copy font size / root font size.
    pub copy_font_ratio: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct GridIntent {
    pub columns: u32,
    pub items: u32,
    pub item_aspect: (u32, u32),
    pub gap_em: f64,
    /// Hover lift mechanism on every item.
    pub hover_lift_px: u32,
    pub hover_easing: String,
    pub hover_duration_ms: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DesignIntent {
    pub name: String,
    pub root_font_px: u32,
    /// Below this viewport width the hero stacks and the grid collapses to one column.
    pub breakpoint_px: u32,
    pub hero: HeroIntent,
    pub grid: GridIntent,
}

const EASINGS: [&str; 5] = ["linear", "ease", "ease-in", "ease-out", "ease-in-out"];

impl DesignIntent {
    /// Structural validity before lowering: positive ratios and a known easing keyword.
    pub fn validate(&self) -> Result<(), String> {
        let positive = |(a, b): (u32, u32)| a > 0 && b > 0;
        if !positive(self.hero.media_aspect) || !positive(self.hero.share) {
            return Err("hero ratios must be positive".into());
        }
        if !positive(self.grid.item_aspect) || self.grid.columns == 0 || self.grid.items == 0 {
            return Err("grid ratios and counts must be positive".into());
        }
        if self.breakpoint_px < 2 || self.root_font_px == 0 {
            return Err("breakpoint and root font size must be positive".into());
        }
        if !EASINGS.contains(&self.grid.hover_easing.as_str()) {
            return Err(format!("unknown easing `{}`", self.grid.hover_easing));
        }
        if !(self.hero.gap_em.is_finite()
            && self.grid.gap_em.is_finite()
            && self.hero.copy_font_ratio > 0.0)
        {
            return Err("spacing and font ratios must be finite and positive".into());
        }
        Ok(())
    }
}

/// Deterministic lowering to one self-contained HTML document (no external requests).
/// Structure: `body>section:1` = hero (`div:1` media, `div:2` copy); `body>section:2` = grid.
pub fn lower_to_html(intent: &DesignIntent) -> String {
    let hero = &intent.hero;
    let grid = &intent.grid;
    let narrow = intent.breakpoint_px - 1;
    let items: String = (1..=grid.items)
        .map(|i| format!("    <div class=\"item\">Item {i}</div>\n"))
        .collect();
    format!(
        r#"<!doctype html>
<!-- Generated by Atlas Creator Fabric from design intent "{name}" (ADR 0017). Placeholder
     content only. -->
<html>
<head>
<meta charset="utf-8">
<style>
  html {{ font-size: {root}px; }}
  body {{ margin: 0; font-family: sans-serif; }}
  .hero {{ display: flex; flex-direction: row; column-gap: {hero_gap}em; padding: 0 2em; }}
  .hero .media {{ flex: {media_share} 1 0; aspect-ratio: {aw} / {ah}; background: #4a5a6a; }}
  .hero .copy {{ flex: {copy_share} 1 0; font-size: {copy_font}rem; }}
  .grid {{ display: grid; grid-template-columns: repeat({columns}, 1fr); column-gap: {grid_gap}em; row-gap: {grid_gap}em; padding: 2em; }}
  .item {{ aspect-ratio: {iw} / {ih}; background: #dde; cursor: pointer;
           transition: transform {duration}ms {easing}; }}
  .item:hover {{ transform: translateY(-{lift}px); }}
  @media (max-width: {narrow}px) {{
    .hero {{ flex-direction: column; }}
    .grid {{ grid-template-columns: 1fr; }}
  }}
</style>
</head>
<body>
  <section class="hero">
    <div class="media"></div>
    <div class="copy">Placeholder heading</div>
  </section>
  <section class="grid">
{items}  </section>
</body>
</html>
"#,
        name = intent.name,
        root = intent.root_font_px,
        hero_gap = hero.gap_em,
        media_share = hero.share.0,
        copy_share = hero.share.1,
        aw = hero.media_aspect.0,
        ah = hero.media_aspect.1,
        copy_font = hero.copy_font_ratio,
        columns = grid.columns,
        grid_gap = grid.gap_em,
        iw = grid.item_aspect.0,
        ih = grid.item_aspect.1,
        duration = grid.hover_duration_ms,
        easing = grid.hover_easing,
        lift = grid.hover_lift_px,
    )
}

/// One intended relation checked against the rendered, re-observed artifact.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct IntentCheck {
    pub intent: String,
    pub expected: String,
    pub measured: String,
    pub verdict: ConstraintVerdict,
}

/// Everything the instrument measured on the rendered artifact.
pub struct RenderedEvidence<'a> {
    /// Layout observed at a wide and a narrow viewport (either side of the breakpoint).
    pub layout: &'a VisualObservationReport,
    /// Breakpoints measured by bisection: (element, change, narrow_width, wide_width).
    pub breakpoints: &'a [(String, ResponsiveChange, u32, u32)],
    pub interactions: &'a InteractionAnalysis,
    pub motion: &'a [MotionInference],
}

pub(crate) fn element<'a>(
    report: &'a VisualObservationReport,
    viewport_width: u32,
    path: &str,
) -> Option<&'a super::ElementObservation> {
    report
        .viewports
        .iter()
        .find(|v| v.width == viewport_width)?
        .elements
        .iter()
        .find(|e| e.path == path)
}

fn ratio_check(intent: &str, expected: f64, measured: Option<(f64, f64)>) -> IntentCheck {
    // `measured` = (numerator, denominator) in px; tolerance from the 1/64 px layout grid.
    match measured {
        Some((num, den)) if den > 0.0 => {
            let value = num / den;
            let e = super::LAYOUT_RESOLUTION_PX;
            let tolerance = ((num + e) / (den - e) - value).abs().max(1e-9);
            IntentCheck {
                intent: intent.into(),
                expected: format!("{expected:.6}"),
                measured: format!("{value:.6} (±{tolerance:.2e})"),
                verdict: if (value - expected).abs() <= tolerance {
                    ConstraintVerdict::Satisfied
                } else {
                    ConstraintVerdict::Violated
                },
            }
        }
        _ => IntentCheck {
            intent: intent.into(),
            expected: format!("{expected:.6}"),
            measured: "not observed".into(),
            verdict: ConstraintVerdict::Unknown,
        },
    }
}

/// Verifies every intended relation of `intent` against the evidence observed on its rendered
/// lowering (`wide`/`narrow` = the two layout viewport widths, on either side of the breakpoint).
pub fn verify_intent(
    intent: &DesignIntent,
    evidence: &RenderedEvidence<'_>,
    wide: u32,
    narrow: u32,
) -> Vec<IntentCheck> {
    let mut checks = Vec::new();
    let (media, copy) = ("body>section:1>div:1", "body>section:1>div:2");
    let first_item = "body>section:2>div:1";
    let hero = &intent.hero;
    let grid = &intent.grid;
    for width in [wide, narrow] {
        checks.push(ratio_check(
            &format!(
                "hero media aspect {}:{} @{width}",
                hero.media_aspect.0, hero.media_aspect.1
            ),
            f64::from(hero.media_aspect.0) / f64::from(hero.media_aspect.1),
            element(evidence.layout, width, media).map(|e| (e.width, e.height)),
        ));
        checks.push(ratio_check(
            &format!(
                "grid item aspect {}:{} @{width}",
                grid.item_aspect.0, grid.item_aspect.1
            ),
            f64::from(grid.item_aspect.0) / f64::from(grid.item_aspect.1),
            element(evidence.layout, width, first_item).map(|e| (e.width, e.height)),
        ));
    }
    checks.push(ratio_check(
        &format!("hero share {}:{} @{wide}", hero.share.0, hero.share.1),
        f64::from(hero.share.0) / f64::from(hero.share.0 + hero.share.1),
        element(evidence.layout, wide, media)
            .zip(element(evidence.layout, wide, copy))
            .map(|(m, c)| (m.width, m.width + c.width)),
    ));
    let copy_font = element(evidence.layout, wide, copy).and_then(|e| {
        e.style
            .get("font-size")?
            .strip_suffix("px")?
            .parse::<f64>()
            .ok()
    });
    checks.push(ratio_check(
        "copy font / root font",
        hero.copy_font_ratio,
        copy_font.map(|px| (px, f64::from(intent.root_font_px))),
    ));
    let rule = |element: &str, change: &ResponsiveChange| {
        evidence
            .breakpoints
            .iter()
            .find(|(e, c, _, _)| e == element && c == change)
    };
    for (element_path, change, label) in [
        (
            "body>section:1",
            ResponsiveChange::FlexDirection {
                narrow: "column".into(),
                wide: "row".into(),
            },
            "hero stacks",
        ),
        (
            "body>section:2",
            ResponsiveChange::GridColumns {
                narrow: 1,
                wide: grid.columns as usize,
            },
            "grid collapses",
        ),
    ] {
        let expected = format!("({}, {})", intent.breakpoint_px - 1, intent.breakpoint_px);
        let (measured, verdict) = match rule(element_path, &change) {
            Some((_, _, lo, hi))
                if (*lo, *hi) == (intent.breakpoint_px - 1, intent.breakpoint_px) =>
            {
                (format!("({lo}, {hi})"), ConstraintVerdict::Satisfied)
            }
            Some((_, _, lo, hi)) => (format!("({lo}, {hi})"), ConstraintVerdict::Violated),
            None => (
                "no such change observed".into(),
                ConstraintVerdict::Violated,
            ),
        };
        checks.push(IntentCheck {
            intent: format!("{label} at breakpoint {}px", intent.breakpoint_px),
            expected,
            measured,
            verdict,
        });
    }
    let lifts = (1..=grid.items)
        .filter(|i| {
            evidence.interactions.mechanisms.iter().any(|m| {
                matches!(m, InteractionMechanism::HoverAffordance { target, properties }
                    if *target == format!("body>section:2>div:{i}")
                        && properties.contains(&"transform".to_owned()))
            })
        })
        .count();
    checks.push(IntentCheck {
        intent: "every grid item has a hover-lift affordance".into(),
        expected: grid.items.to_string(),
        measured: lifts.to_string(),
        verdict: if lifts == grid.items as usize {
            ConstraintVerdict::Satisfied
        } else {
            ConstraintVerdict::Violated
        },
    });
    let item_motion: Vec<&MotionInference> = evidence
        .motion
        .iter()
        .filter(|m| m.element.starts_with("body>section:2>div:"))
        .collect();
    let easing_ok = !item_motion.is_empty()
        && item_motion.iter().all(|m| {
            m.inferred_easing.as_deref() == Some(grid.hover_easing.as_str())
                && (m.duration_ms - f64::from(grid.hover_duration_ms)).abs() < 1e-6
        });
    checks.push(IntentCheck {
        intent: "hover motion easing and duration (inferred from sampled curves)".into(),
        expected: format!("{} {}ms", grid.hover_easing, grid.hover_duration_ms),
        measured: item_motion
            .iter()
            .map(|m| {
                format!(
                    "{} {}ms",
                    m.inferred_easing.as_deref().unwrap_or("none"),
                    m.duration_ms
                )
            })
            .collect::<Vec<_>>()
            .join(", "),
        verdict: if item_motion.is_empty() {
            ConstraintVerdict::Unknown
        } else if easing_ok {
            ConstraintVerdict::Satisfied
        } else {
            ConstraintVerdict::Violated
        },
    });
    checks
}

#[cfg(test)]
mod tests {
    use super::*;

    pub(crate) fn intent() -> DesignIntent {
        DesignIntent {
            name: "test".into(),
            root_font_px: 16,
            breakpoint_px: 820,
            hero: HeroIntent {
                media_aspect: (3, 2),
                share: (3, 2),
                gap_em: 1.5,
                copy_font_ratio: 1.5,
            },
            grid: GridIntent {
                columns: 4,
                items: 4,
                item_aspect: (1, 1),
                gap_em: 1.0,
                hover_lift_px: 6,
                hover_easing: "ease-in-out".into(),
                hover_duration_ms: 200,
            },
        }
    }

    #[test]
    fn lowering_is_deterministic_self_contained_and_placeholder_only() {
        let html = lower_to_html(&intent());
        assert_eq!(html, lower_to_html(&intent()));
        assert!(html.contains("aspect-ratio: 3 / 2"));
        assert!(html.contains("repeat(4, 1fr)"));
        assert!(html.contains("@media (max-width: 819px)"));
        assert!(html.contains("transition: transform 200ms ease-in-out"));
        assert!(!html.contains("http"), "no external resource of any kind");
        assert!(!html.contains("<img") && !html.contains("<link") && !html.contains("<script"));
    }

    #[test]
    fn invalid_intents_are_rejected_before_lowering() {
        let mut bad = intent();
        bad.grid.hover_easing = "bouncy".into();
        assert!(bad.validate().is_err());
        let mut bad = intent();
        bad.hero.media_aspect = (0, 9);
        assert!(bad.validate().is_err());
        assert!(intent().validate().is_ok());
    }
}
