//! The document budget: sprawl is detected and classified, knowledge is extracted before any
//! deletion, and only extracted, unchanged documents are ever pruned.

mod common;

use common::*;
use ynventa::audit::Issue;

fn issues(a: &ynventa::Assessment, path: &str) -> Vec<Issue> {
    a.docs
        .docs
        .iter()
        .find(|d| d.path == path)
        .unwrap_or_else(|| panic!("{path} not audited"))
        .issues
        .clone()
}

#[test]
fn sprawl_is_classified_extracted_then_pruned() {
    let r = extinct_baseline("docs");
    r.write(
        "substrate/geo/README.md",
        "# geo\n\nNative planar geometry.\n",
    );
    let shared = "- The geometry kernel is planar only.\n- Distances are Euclidean in metres.\n- Every projection is explicit.\n- Coordinates are never implicitly converted.\n";
    r.write("core/NOTES.md", &format!("# Notes\n\n{shared}"));
    r.write("substrate/geo/NOTES.md", &format!("# Notes\n\n{shared}"));
    r.write(
        "tests/geo-summary.md",
        &format!("# Summary\n\n{shared}- One extra remark about tests.\n"),
    );
    r.write(
        "tests/SESSION-2026-09-30.md",
        "# Session\n\n- iteration 14 ran the census\n",
    );
    r.write(
        "tests/CENSUS-REPORT.md",
        "<!-- GENERATED by census: do not edit -->\n# Census\n\n- 12 crates\n",
    );
    r.write(
        "core/decisions/0001-old.md",
        "# Use floats\n\nStatus: superseded by 0002\n\n- Distances are floats.\n",
    );
    r.write(
        "core/architecture/overview.md",
        "# Overview\n\nSee `gone/a.rs`, `missing/b.rs` and `core/src/lib.rs`.\n",
    );
    let a = r.assess();
    assert!(
        a.docs
            .docs
            .iter()
            .find(|d| d.path == "substrate/geo/README.md")
            .unwrap()
            .allowed,
        "a node README is in budget"
    );
    assert!(
        a.docs
            .docs
            .iter()
            .find(|d| d.path == "README.md")
            .unwrap()
            .allowed
    );
    assert!(
        issues(&a, "substrate/geo/NOTES.md").contains(&Issue::Duplicate("core/NOTES.md".into()))
    );
    assert!(issues(&a, "core/NOTES.md")
        .iter()
        .any(|i| matches!(i, Issue::NearDuplicate(_, p) if *p >= 80)));
    assert!(
        !issues(&a, "tests/geo-summary.md")
            .iter()
            .any(|i| matches!(i, Issue::NearDuplicate(..))),
        "the superset is kept"
    );
    assert!(issues(&a, "tests/SESSION-2026-09-30.md").contains(&Issue::SessionLog));
    assert!(issues(&a, "tests/CENSUS-REPORT.md").contains(&Issue::GeneratedCommitted));
    assert!(issues(&a, "core/decisions/0001-old.md").contains(&Issue::Superseded));
    assert!(issues(&a, "core/architecture/overview.md").contains(&Issue::StaleArchitecture(2, 3)));
    assert_eq!(a.metric("documents_over_budget"), "7");
    assert_ne!(a.metric("repository_shape_conformance"), "1.000000");

    // Pruning before extraction deletes nothing.
    assert_eq!(r.cli(&["compact", "--prune-docs"]).0, 0);
    assert!(r.exists("core/NOTES.md"));

    // Extraction: one fact per distinct statement, every provenance kept.
    assert_eq!(r.cli(&["compact", "--extract-docs"]).0, 0);
    let a = r.assess();
    let planar = a
        .knowledge
        .facts
        .iter()
        .find(|f| f.value == "The geometry kernel is planar only.")
        .unwrap();
    assert_eq!(planar.provenance.len(), 3);
    assert!(a.docs.over_budget().all(|d| d.extracted));
    assert!(issues(&a, "core/NOTES.md")
        .iter()
        .any(|i| matches!(i, Issue::Represented(100))));

    // A document edited after extraction is not pruned: its new knowledge is not yet kept.
    r.write(
        "core/NOTES.md",
        &format!("# Notes\n\n{shared}- A new, unique remark.\n"),
    );
    assert_eq!(r.cli(&["compact", "--prune-docs"]).0, 0);
    assert!(r.exists("core/NOTES.md"));
    assert!(!r.exists("substrate/geo/NOTES.md") && !r.exists("tests/SESSION-2026-09-30.md"));
    assert!(r.exists("substrate/geo/README.md") && r.exists("README.md"));
    assert_eq!(r.cli(&["compact", "--extract-docs", "--prune-docs"]).0, 0);
    assert!(!r.exists("core/NOTES.md"));
    let a = r.assess();
    assert!(a
        .knowledge
        .facts
        .iter()
        .any(|f| f.value == "A new, unique remark."));
    assert_eq!(a.metric("documents_over_budget"), "0");
    assert_eq!(a.metric("repository_shape_conformance"), "1.000000");
}
