/*
 * clcu.h — IRIS L3 Hardware Materialization Engine
 *
 * CLCU: Compact 64-byte bytecode container optimized for cache-friendly
 * sequential decoding. Container format, execution state, FFI structs,
 * and opcode defines.
 *
 * See SPEC.md Sections 8.5, 9.1–9.8, 9.10.
 */
#ifndef CLCU_H
#define CLCU_H

#include <stdint.h>
#include <stddef.h>

#ifdef __AVX512F__
#include <immintrin.h>
#endif

/* ────────────────────────────────────────────────────────────────────────────
 * Container flag defines (flags byte at offset 0x03)
 * ──────────────────────────────────────────────────────────────────────────── */
#define CLCU_FLAG_IS_ENTRY       (1 << 7)  /* Container is a chain entry point       */
#define CLCU_FLAG_IS_CONTINUATION (1 << 6) /* More containers follow in this unit    */
#define CLCU_FLAG_PREFETCH_VALID (1 << 5)  /* prefetch_target field is valid         */
#define CLCU_FLAG_HAS_RELOCATION (1 << 4)  /* Container was rewritten by rewrite system */
#define CLCU_FLAG_MASK_SOURCE_MASK 0x0C    /* bits [3:2]: mask source                */
#define CLCU_FLAG_MASK_IMM       (0 << 2)  /* 00 = immediate mask in mask_immediate  */
#define CLCU_FLAG_MASK_REG       (1 << 2)  /* 01 = mask register k[mask_immediate&7] */
#define CLCU_FLAG_MASK_MEM       (2 << 2)  /* 10 = mask loaded from memory           */
#define CLCU_FLAG_MASK_COMPUTED  (3 << 2)  /* 11 = mask generated by VCMP in payload */

/* Sentinel values for next_container */
#define CLCU_NEXT_SEQUENTIAL     0          /* Next cache line                       */
#define CLCU_NEXT_TERMINAL       0x7FFFFFFF /* End of chain                          */
#define CLCU_NEXT_YIELD          0x7FFFFFFE /* Yield to runtime (effect trampoline)  */

/* Magic nibble and version encoding in magic_and_version (2 bytes):
 *   [15:12] = 0xC  (magic)
 *   [11:8]  = version (0-15)
 *   [7:0]   = unit_length_in_containers (1-255)
 */
#define CLCU_MAGIC_NIBBLE        0xC
#define CLCU_VERSION             0x1

/* ────────────────────────────────────────────────────────────────────────────
 * CLCU micro-op opcode defines (~50 opcodes from SPEC Section 1.6)
 *
 * Range 0x00-0x0F: Arithmetic / vector compute
 * Range 0x10-0x1F: Bitwise / shifts
 * Range 0x20-0x2F: Comparison / mask generation
 * Range 0x30-0x3F: Memory / data movement
 * Range 0x40-0x4F: Conversion / special
 * Range 0x80-0xFF: Reserved for rewrite-system-generated operations
 * ──────────────────────────────────────────────────────────────────────────── */

/* Arithmetic / vector compute */
#define OP_NOP          0x00
#define OP_VADD         0x01
#define OP_VMUL         0x02
#define OP_VFMA         0x03
#define OP_VSUB         0x04
#define OP_VDIV         0x05
#define OP_VMOD         0x06
#define OP_VNEG         0x07
#define OP_VABS         0x08
#define OP_VMIN         0x09
#define OP_VMAX         0x0A
#define OP_VPOW         0x0B
#define OP_VREDUCE      0x0C
#define OP_VBROADCAST   0x0D
#define OP_VPERMUTE     0x0E
#define OP_VBLEND       0x0F

/* Bitwise / shifts */
#define OP_VAND         0x10
#define OP_VOR          0x11
#define OP_VXOR         0x12
#define OP_VNOT         0x13
#define OP_VSHL         0x14
#define OP_VSHR         0x15
#define OP_VSAR         0x16
#define OP_VROTL        0x17
#define OP_VROTR        0x18
#define OP_VCALL        0x19  /* External call (neural >16K params) */
#define OP_VPOPCOUNT    0x1A
#define OP_VCLZ         0x1B

/* Comparison / mask generation */
#define OP_VCMP         0x20
#define OP_VCMP_EQ      0x21
#define OP_VCMP_NE      0x22
#define OP_VCMP_LT      0x23
#define OP_VCMP_GT      0x24
#define OP_VCMP_LE      0x25
#define OP_VCMP_GE      0x26
#define OP_VMOVMASK     0x27  /* Move mask to/from k-register */

/* Memory / data movement */
#define OP_VLOAD        0x30
#define OP_VSTORE       0x31
#define OP_VLOAD_MASK   0x32
#define OP_VSTORE_MASK  0x33
#define OP_VGATHER      0x34
#define OP_VSCATTER     0x35
#define OP_VEXTRACT     0x36
#define OP_VINSERT      0x37
#define OP_VSHUF_CROSS  0x38

/* Conversion / special */
#define OP_VCONVERT     0x40  /* int<->float, width changes */
#define OP_INT_TO_FLOAT 0x41
#define OP_FLOAT_TO_INT 0x42
#define OP_VWIDEN       0x43
#define OP_VNARROW      0x44
#define OP_VBOOL_TO_INT 0x45

/* Reduce operation modifiers (in the 'modifier' field for OP_VREDUCE) */
#define REDUCE_ADD      0x0
#define REDUCE_MUL      0x1
#define REDUCE_MIN      0x2
#define REDUCE_MAX      0x3
#define REDUCE_AND      0x4
#define REDUCE_OR       0x5
#define REDUCE_XOR      0x6

/* Compare modifiers (for OP_VCMP) */
#define CMP_EQ          0x0
#define CMP_NE          0x4
#define CMP_LT          0x1
#define CMP_LE          0x2
#define CMP_GT          0x6  /* swapped NLE */
#define CMP_GE          0x5  /* swapped NLT */

/* Width encoding (bits [6:4] of byte 2 in micro-op) */
#define WIDTH_8B        0
#define WIDTH_16B       1
#define WIDTH_32B       2
#define WIDTH_64B       3
#define WIDTH_128B      4
#define WIDTH_256B      5
#define WIDTH_512B      6
#define WIDTH_CUSTOM    7

/* ZMM register partitions (SPEC Section 9.3) */
#define ZMM_COMPUTE_LO  0   /* zmm0-7:   compute registers              */
#define ZMM_COMPUTE_HI  7
#define ZMM_SPILL_LO     8  /* zmm8-15:  spill/reload                   */
#define ZMM_SPILL_HI     15
#define ZMM_STAGING_LO   16 /* zmm16-23: data staging (gather/scatter)  */
#define ZMM_STAGING_HI   23
#define ZMM_CONST_LO     24 /* zmm24-27: constant pool                  */
#define ZMM_CONST_HI     27
#define ZMM_ACCUM_LO     28 /* zmm28-29: accumulators                   */
#define ZMM_ACCUM_HI     29
#define ZMM_SCRATCH      30 /* zmm30:    scratch                        */
#define ZMM_ZERO         31 /* zmm31:    always zero                    */

/* Max micro-ops per container payload (48 bytes / 6 bytes each) */
#define CLCU_MAX_MICRO_OPS  8
#define CLCU_MICRO_OP_SIZE  6
#define CLCU_PAYLOAD_SIZE   48
#define CLCU_HEADER_SIZE    16
#define CLCU_CONTAINER_SIZE 64

/* ────────────────────────────────────────────────────────────────────────────
 * CLCU Container — 64 bytes, cache-line sized (SPEC Section 9.1)
 * ──────────────────────────────────────────────────────────────────────────── */
typedef struct __attribute__((packed, aligned(64))) clcu_container {
    /* 16-byte header */
    uint16_t magic_and_version;  /* [15:12]=0xC magic, [11:8]=version, [7:0]=unit_length */
    uint8_t  container_index;    /* Position within multi-container unit (0-based) */
    uint8_t  flags;              /* CLCU_FLAG_* defines                             */
    int32_t  next_container;     /* Relative offset to next, in 64-byte units       */
    int32_t  prefetch_target;    /* Relative offset to prefetch, in 64-byte units   */
    uint16_t mask_immediate;     /* 16-bit predication mask (when mask_source=00)   */
    uint8_t  zmm_live_in;        /* Bitmask of ZMM regs read (zmm0-zmm7)           */
    uint8_t  zmm_live_out;       /* Bitmask of ZMM regs written (zmm0-zmm7)        */

    /* 48-byte payload: up to 8 micro-ops at 6 bytes each */
    uint8_t  payload[CLCU_PAYLOAD_SIZE];
} clcu_container_t;

_Static_assert(sizeof(clcu_container_t) == 64,
               "CLCU container must be exactly 64 bytes");

/* ────────────────────────────────────────────────────────────────────────────
 * Micro-op field extraction helpers
 *
 * Byte layout per 6-byte micro-op:
 *   [0]   opcode
 *   [1]   [7:5]=dst_reg  [4:2]=src1_reg  [1:0]=src2_reg_hi
 *   [2]   [7]=src2_reg_lo  [6:4]=width  [3:0]=modifier
 *   [3-5] immediate (24-bit, little-endian)
 * ──────────────────────────────────────────────────────────────────────────── */
static inline uint8_t  uop_opcode(const uint8_t *op)   { return op[0]; }
static inline uint8_t  uop_dst(const uint8_t *op)      { return (op[1] >> 5) & 0x7; }
static inline uint8_t  uop_src1(const uint8_t *op)     { return (op[1] >> 2) & 0x7; }
static inline uint8_t  uop_src2(const uint8_t *op)     { return ((op[1] & 0x3) << 1) | ((op[2] >> 7) & 0x1); }
static inline uint8_t  uop_width(const uint8_t *op)    { return (op[2] >> 4) & 0x7; }
static inline uint8_t  uop_modifier(const uint8_t *op) { return op[2] & 0xF; }
static inline uint32_t uop_immediate(const uint8_t *op) {
    return (uint32_t)op[3] | ((uint32_t)op[4] << 8) | ((uint32_t)op[5] << 16);
}

/* ────────────────────────────────────────────────────────────────────────────
 * Execution state — ZMM register file + mask registers + PC + flags
 * ──────────────────────────────────────────────────────────────────────────── */
typedef struct __attribute__((aligned(64))) exec_state {
#ifdef __AVX512F__
    __m512i  zmm[32];          /* 32 x 512-bit ZMM registers      */
    __mmask16 k[8];            /* 8 mask registers k0-k7           */
#else
    /* Scalar fallback: 32 x 16 x int32 = 32 x 64 bytes */
    int32_t  zmm[32][16];
    uint16_t k[8];             /* 16-bit mask registers            */
#endif
    const clcu_container_t *pc; /* Current container pointer       */
    uint64_t cycle_count;       /* Accumulated cycle count         */
    uint32_t status_flags;      /* Execution status                */
    uint32_t containers_executed; /* Counter for profiling         */
} exec_state_t;

/* Status flags for exec_state_t */
#define EXEC_STATUS_OK        0x0
#define EXEC_STATUS_HALTED    0x1
#define EXEC_STATUS_FAULT     0x2
#define EXEC_STATUS_YIELDED   0x4

/* ────────────────────────────────────────────────────────────────────────────
 * eval_result_ffi_t — C-Compatible FFI Layout (SPEC Section 8.5)
 * 128 bytes = 2 cache lines, exactly as specified
 * ──────────────────────────────────────────────────────────────────────────── */
typedef struct __attribute__((aligned(64))) eval_result_ffi {
    /* Cache line 1 (64 bytes): timing + correctness */
    uint64_t wall_time_ns;
    uint64_t compile_time_ns;
    uint64_t instructions_retired;
    uint64_t cycles;
    uint64_t outputs_hash;
    float    correctness_score;
    float    ipc;
    uint32_t tests_passed;
    uint32_t tests_total;
    uint8_t  tier_executed;
    uint8_t  cache_hit;
    uint8_t  counters_valid;
    uint8_t  _pad1;
    uint32_t graph_hash_lo;

    /* Cache line 2 (64 bytes): hardware counters */
    float    l1d_miss_rate;
    float    llc_miss_rate;
    float    dtlb_miss_rate;
    float    branch_miss_rate;
    uint64_t l1d_misses;
    uint64_t l1d_accesses;
    uint64_t llc_misses;
    uint64_t branch_misses;
    uint64_t dtlb_misses;
    uint64_t _reserved[1];
} eval_result_ffi_t;

_Static_assert(sizeof(eval_result_ffi_t) == 128,
               "eval_result_ffi_t must be exactly 128 bytes (2 cache lines)");

/* ────────────────────────────────────────────────────────────────────────────
 * Arena allocator (forward declarations)
 * ──────────────────────────────────────────────────────────────────────────── */
#define ARENA_SIZE       (2 * 1024 * 1024)  /* 2MB huge page */
#define CONTAINERS_PER_ARENA (ARENA_SIZE / CLCU_CONTAINER_SIZE) /* 32768 */

typedef struct {
    void     *base;       /* mmap'd base, 2MB-aligned   */
    uint32_t  next_free;  /* Next free container index   */
    uint32_t  capacity;   /* CONTAINERS_PER_ARENA        */
} clcu_arena_t;

clcu_arena_t *arena_create(void);
void         *arena_alloc(clcu_arena_t *arena, uint32_t n);
void          arena_destroy(clcu_arena_t *arena);

/* ────────────────────────────────────────────────────────────────────────────
 * Interpreter (forward declarations)
 * ──────────────────────────────────────────────────────────────────────────── */
typedef void (*microop_fn)(exec_state_t *state, uint8_t dst, uint8_t src1,
                           uint8_t src2, uint8_t width, uint8_t modifier,
                           uint32_t immediate);

void interpreter_init(void);
void execute_container(exec_state_t *state, const clcu_container_t *c);
void execute_chain(exec_state_t *state, const clcu_container_t *entry);

/* Alias matching SPEC Section 9.10 */
static inline void interpreter_run(const clcu_container_t *entry, exec_state_t *regs) {
    execute_chain(regs, entry);
}

/* ────────────────────────────────────────────────────────────────────────────
 * DEPRECATED: TLB-encoded hash map (forward declarations)
 *
 * The TLB-as-data-structure approach was identified by the engineering
 * council as a category error. User-space cannot control TLB behavior.
 * This code is retained for reference but should not be used in production.
 * Use standard HashMap implementations instead.
 * ──────────────────────────────────────────────────────────────────────────── */
typedef struct tlb_map tlb_map_t;

tlb_map_t  *tlb_map_create(uint32_t key_size, uint32_t value_size,
                            uint64_t expected_entries);
void        tlb_map_destroy(tlb_map_t *map);
int         tlb_map_insert(tlb_map_t *map, const void *key, const void *value);
const void *tlb_map_lookup(const tlb_map_t *map, const void *key);
int         tlb_map_delete(tlb_map_t *map, const void *key);
void        tlb_map_prefetch(const tlb_map_t *map, const void *key);

/* ────────────────────────────────────────────────────────────────────────────
 * TSO lock-free ring buffer (forward declarations)
 * ──────────────────────────────────────────────────────────────────────────── */
#define TSO_RING_SIZE      1024  /* Must be power of 2 */
#define TSO_RING_MASK      (TSO_RING_SIZE - 1)
#define TSO_SLOT_DATA_SIZE 48
#define TSO_SPIN_LIMIT     100

typedef struct __attribute__((aligned(64))) {
    volatile uint64_t sequence;
    uint8_t  data[TSO_SLOT_DATA_SIZE];
    uint64_t _padding;
} tso_slot_t;

_Static_assert(sizeof(tso_slot_t) == 64,
               "TSO slot must be exactly 64 bytes (1 cache line)");

typedef struct tso_ring tso_ring_t;

tso_ring_t *tso_ring_create(void);
void        tso_ring_destroy(tso_ring_t *ring);
int         tso_produce(tso_ring_t *ring, const void *data, size_t len);
int         tso_consume(tso_ring_t *ring, void *data, size_t len);

#endif /* CLCU_H */
