module BackEnd.MCU.Layout

open System.IO
open Core.Types.Pipeline

let origin (space: BAREWire.Platform.MemorySpace) = space.Base |> Option.defaultWith (fun () -> failwith ("No base for " + space.Name))

let generate (target: EmbeddedTarget) destination =
    Directory.CreateDirectory destination |> ignore
    let flash, ram = target.Flash, target.Ram
    let stackTop = origin ram + ram.Capacity
    let stackBottom = stackTop - int64 target.Image.StackBytes
    let script = (sprintf """/* Generated by Composer from BAREWire declarations; do not edit. */
ENTRY(%s)
MEMORY {
  FLASH (rx) : ORIGIN = 0x%X, LENGTH = 0x%X
  RAM (rw) : ORIGIN = 0x%X, LENGTH = 0x%X
}
__stack_top = 0x%X;
__stack_bottom = 0x%X;
SECTIONS {
  .vectors ORIGIN(FLASH) : ALIGN(%d) { KEEP(*(.vectors)) } > FLASH
  .text : ALIGN(4) { *(.text*) *(.rodata*) } > FLASH
  .data : ALIGN(8) {
    __data_start = .; *(.data*) . = ALIGN(4); __data_end = .;
  } > RAM AT> FLASH
  __data_load = LOADADDR(.data);
  .bss (NOLOAD) : ALIGN(8) {
    __bss_start = .; *(.bss*) *(COMMON) . = ALIGN(4); __bss_end = .;
  } > RAM
  .noinit (NOLOAD) : ALIGN(8) { *(.noinit*) } > RAM
  __ram_end = .;
  .stack __stack_bottom (NOLOAD) : { . += %d; } > RAM
  /DISCARD/ : { *(.comment) *(.note*) *(.ARM.exidx*) *(.ARM.extab*) *(.eh_frame*) }
}
ASSERT(SIZEOF(.vectors) == %d, "Wrong vector count")
ASSERT((ADDR(.vectors) & (%d - 1)) == 0, "Misaligned VTOR")
ASSERT(__ram_end <= __stack_bottom, "Data/stack collision")
ASSERT(LOADADDR(.data) + SIZEOF(.data) <= ORIGIN(FLASH) + LENGTH(FLASH), "Flash overflow")
""" target.Image.EntrySymbol (origin flash) flash.Capacity (origin ram) ram.Capacity stackTop stackBottom
            target.Image.VectorAlignment target.Image.StackBytes target.Vectors.Layout.Size target.Image.VectorAlignment)
    File.WriteAllText(Path.Combine(destination, "memory.ld"), script)
    File.WriteAllText(Path.Combine(destination, "layout.inc"), sprintf ".equ VECTOR_COUNT, %d\n.equ VECTOR_ALIGNMENT, %d\n.equ RAM_ORIGIN, 0x%X\n" (target.Vectors.Layout.Size / 4) target.Image.VectorAlignment (origin ram))
    Tools.writeJson (Path.Combine(destination, "layout.json"))
        {| platform = target.PlatformId; flashOrigin = origin flash; flashBytes = flash.Capacity
           ramOrigin = origin ram; ramBytes = ram.Capacity; stackBottom = stackBottom; stackTop = stackTop
           vectorBytes = target.Vectors.Layout.Size; vectorAlignment = target.Image.VectorAlignment |}
