//! Cargo dependency census: a minimal, dedicated `Cargo.lock`/`Cargo.toml` reader.
//!
//! `Cargo.lock` is machine-generated with a small, stable subset of TOML (see its own header
//! comment: "This file is automatically @generated by Cargo. It is not intended for manual
//! editing."), and each `Cargo.toml` dependency table this parser reads is a bounded, well-known
//! shape (`.atlas/contracts/DEPENDENCY-CENSUS.md`). A dedicated parser for exactly these shapes
//! avoids adding a general TOML-parsing dependency merely to bootstrap dependency census itself
//! (a new crate to census dependencies would itself immediately need census).
//!
//! Only what these two file shapes literally state is recorded. A dependency name appearing in a
//! `Cargo.lock` package's own `dependencies` list with no corresponding `[[package]]` entry is a
//! dangling reference, never silently dropped. A transitive edge between two external (non-
//! workspace) packages never gets a guessed `DependencyKind`: this parser never fetches or reads
//! an external crate's own manifest, so it cannot know which of that crate's own dependency
//! tables the edge came from.

use atlas_core::{
    DependencyClosureReport, DependencyClosureState, DependencyEcosystem, DependencyEdge,
    DependencyIdentity, DependencyKind, DependencySourceKind, DynamicDependencyObligation,
};
use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    io::{self, ErrorKind},
    path::Path,
};

#[derive(Debug, Clone, Default)]
struct LockPackage {
    name: String,
    version: String,
    source: Option<String>,
    checksum: Option<String>,
    dependencies: Vec<LockDependencyRef>,
}

/// One `Cargo.lock` `dependencies` array entry. Cargo emits a bare `"name"` when exactly one
/// resolved version of that name exists in the lockfile, and disambiguates with a resolved
/// version as `"name version"` (or `"name version (source)"`) whenever more than one does. The
/// `(source)` suffix, needed only when the same name *and* version resolve from two different
/// sources, is not parsed yet -- a named, documented, not-yet-exercised gap distinct from the
/// version disambiguation this type exists to carry.
#[derive(Debug, Clone, PartialEq, Eq)]
struct LockDependencyRef {
    name: String,
    version: Option<String>,
}

/// The value of `key = "..."` on `line`, if `line` is exactly that assignment.
fn quoted_field(line: &str, key: &str) -> Option<String> {
    let rest = line.strip_prefix(key)?.trim_start();
    let rest = rest.strip_prefix('=')?.trim_start();
    let inner = rest.strip_prefix('"')?.strip_suffix('"')?;
    Some(inner.to_owned())
}

/// The bare quoted string inside one `"value"` (or `"value",`) array-entry line, e.g. a
/// `workspace.members` entry. Unlike `lock_dependency_ref`, this never strips a trailing token --
/// a workspace member path has no lockfile-style version suffix to disambiguate.
fn quoted_array_string(line: &str) -> Option<String> {
    let trimmed = line.trim().trim_end_matches(',');
    let inner = trimmed.strip_prefix('"')?.strip_suffix('"')?;
    Some(inner.to_owned())
}

/// One `"name"` or disambiguated `"name version"` lockfile dependency-array entry line.
fn lock_dependency_ref(line: &str) -> Option<LockDependencyRef> {
    let inner = quoted_array_string(line)?;
    let mut tokens = inner.split_whitespace();
    let name = tokens.next()?.to_owned();
    let version = tokens.next().map(str::to_owned);
    Some(LockDependencyRef { name, version })
}

fn parse_cargo_lock(text: &str) -> Vec<LockPackage> {
    let mut packages = Vec::new();
    let mut lines = text.lines().peekable();
    while let Some(line) = lines.next() {
        if line.trim() != "[[package]]" {
            continue;
        }
        let mut package = LockPackage::default();
        while let Some(&next) = lines.peek() {
            let trimmed = next.trim();
            if trimmed.is_empty() || trimmed.starts_with('[') {
                break;
            }
            lines.next();
            if let Some(value) = quoted_field(trimmed, "name") {
                package.name = value;
            } else if let Some(value) = quoted_field(trimmed, "version") {
                package.version = value;
            } else if let Some(value) = quoted_field(trimmed, "source") {
                package.source = Some(value);
            } else if let Some(value) = quoted_field(trimmed, "checksum") {
                package.checksum = Some(value);
            } else if let Some(rest) = trimmed.strip_prefix("dependencies = [") {
                if let Some(inline) = rest.strip_suffix(']') {
                    package.dependencies =
                        inline.split(',').filter_map(lock_dependency_ref).collect();
                } else {
                    while let Some(&dep_line) = lines.peek() {
                        if dep_line.trim() == "]" {
                            lines.next();
                            break;
                        }
                        lines.next();
                        if let Some(dependency_ref) = lock_dependency_ref(dep_line) {
                            package.dependencies.push(dependency_ref);
                        }
                    }
                }
            }
        }
        packages.push(package);
    }
    packages
}

/// The declared array-of-strings value of `workspace.members` in a root `Cargo.toml`, e.g.
/// `members = ["core", "runtime", "adapter", "apps/cli"]`, plus whether a `members` key was found
/// whose value this parser could not read (a multi-line array). Only the single-line array shape
/// is read (Atlas's own root manifest uses it); a multi-line `members = [` array is detected and
/// named explicitly -- distinct from "no workspace declared at all" -- rather than silently
/// treated the same as an empty/absent `members` key, since the caller must know a real workspace
/// exists whose full member list it could not read.
fn workspace_members(root_manifest: &str) -> (Vec<String>, bool) {
    for line in root_manifest.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("members") {
            let rest = rest.trim_start();
            if let Some(rest) = rest.strip_prefix('=') {
                let rest = rest.trim();
                if let Some(inline) = rest.strip_prefix('[').and_then(|r| r.strip_suffix(']')) {
                    return (
                        inline.split(',').filter_map(quoted_array_string).collect(),
                        false,
                    );
                }
                if rest.starts_with('[') {
                    return (Vec::new(), true);
                }
            }
        }
    }
    (Vec::new(), false)
}

/// One `[dependencies]`-shaped table entry: the resolved crate name it actually names (the key
/// itself, unless the entry renames via `package = "..."`, e.g. `atlas_core = { package = "core",
/// path = "../core" }` names the crate `core`, not `atlas_core`) and whether it declares
/// `optional = true`.
struct ManifestDependencyEntry {
    resolved_name: String,
    optional: bool,
}

/// Net count of `{`/`}` in `text` -- used to detect and join an inline table value that spans
/// more than one physical line (e.g. `foo = { version = "1",\n features = ["x"] }`). Adequate for
/// this bounded shape: a Cargo dependency-table value never itself contains a literal brace inside
/// a string (versions/features never do), so counting raw characters cannot be fooled here the way
/// it could be for arbitrary TOML.
fn brace_depth(text: &str) -> i32 {
    text.chars()
        .map(|c| match c {
            '{' => 1,
            '}' => -1,
            _ => 0,
        })
        .sum()
}

fn manifest_dependency_entries(section: &str) -> Vec<ManifestDependencyEntry> {
    let mut entries = Vec::new();
    let lines: Vec<&str> = section.lines().collect();
    let mut index = 0;
    while index < lines.len() {
        let trimmed = lines[index].trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            index += 1;
            continue;
        }
        let Some(eq_pos) = trimmed.find('=') else {
            index += 1;
            continue;
        };
        let key = trimmed[..eq_pos]
            .trim()
            .split('.')
            .next()
            .unwrap_or_default()
            .trim();
        if key.is_empty() {
            index += 1;
            continue;
        }
        let mut value = trimmed[eq_pos + 1..].trim().to_owned();
        // An inline table opened here but not closed on the same line spans further physical
        // lines; join them so `quoted_field_anywhere`/`bool_field_anywhere` see the whole table,
        // not just its first fragment (a bare `package = "..."` or `optional = true` on a later
        // line would otherwise be silently missed).
        let mut depth = brace_depth(&value);
        while depth > 0 {
            index += 1;
            let Some(&next) = lines.get(index) else {
                break;
            };
            value.push(' ');
            value.push_str(next.trim());
            depth += brace_depth(next.trim());
        }
        let resolved_name =
            quoted_field_anywhere(&value, "package").unwrap_or_else(|| key.to_owned());
        let optional = bool_field_anywhere(&value, "optional").unwrap_or(false);
        entries.push(ManifestDependencyEntry {
            resolved_name,
            optional,
        });
        index += 1;
    }
    entries
}

/// Like `quoted_field`, but `key = "value"` may appear anywhere in `text` (inside a `{ ... }`
/// inline table), not only as the whole line.
fn quoted_field_anywhere(text: &str, key: &str) -> Option<String> {
    let needle = format!("{key} = \"");
    let start = text.find(&needle)? + needle.len();
    let end = text[start..].find('"')? + start;
    Some(text[start..end].to_owned())
}

/// Like `quoted_field_anywhere`, but for a bare `key = true`/`key = false` (inline-table booleans
/// are never quoted in TOML).
fn bool_field_anywhere(text: &str, key: &str) -> Option<bool> {
    if text.contains(&format!("{key} = true")) {
        Some(true)
    } else if text.contains(&format!("{key} = false")) {
        Some(false)
    } else {
        None
    }
}

/// Every top-level `[section header]` in `manifest`, paired with its body text (up to the next
/// section header or end of file).
fn manifest_sections(manifest: &str) -> Vec<(&str, String)> {
    let lines: Vec<&str> = manifest.lines().collect();
    let mut sections = Vec::new();
    let mut index = 0;
    while index < lines.len() {
        let trimmed = lines[index].trim();
        if !trimmed.starts_with('[') {
            index += 1;
            continue;
        }
        let start = index + 1;
        let end = lines[start..]
            .iter()
            .position(|line| line.trim_start().starts_with('['))
            .map(|offset| start + offset)
            .unwrap_or(lines.len());
        sections.push((trimmed, lines[start..end].join("\n")));
        index = end;
    }
    sections
}

/// Classifies a manifest section header as a dependency table, if it is one. A bare
/// `[dependencies]`/`[dev-dependencies]`/`[build-dependencies]` table is unconditionally active;
/// the same tables nested under `[target.'cfg(...)'.dependencies]` (any target-selector spelling)
/// are only active for that target, so every dependency declared there is `TargetConditional`
/// regardless of which of the three sub-tables it came from -- this bootstrap does not yet parse
/// or represent the target-selector expression itself, an explicit, documented gap.
fn dependency_section_kind(header: &str) -> Option<DependencyKind> {
    match header {
        "[dependencies]" => Some(DependencyKind::Runtime),
        "[dev-dependencies]" => Some(DependencyKind::Dev),
        "[build-dependencies]" => Some(DependencyKind::Build),
        _ if header.starts_with("[target.")
            && (header.ends_with(".dependencies]")
                || header.ends_with(".dev-dependencies]")
                || header.ends_with(".build-dependencies]")) =>
        {
            Some(DependencyKind::TargetConditional)
        }
        _ => None,
    }
}

/// `(crate_name, DependencyKind)` for every dependency this manifest text directly declares,
/// across every recognized table. An entry declaring `optional = true` is classified `Optional`
/// regardless of which table it came from, since Cargo only actually activates it when the
/// enabling feature is selected -- a fact this bootstrap does not yet model as its own resolution
/// context, so `Optional` here means "declared optional", not "active in this admitted context".
fn manifest_dependency_kinds(manifest: &str) -> Vec<(String, DependencyKind)> {
    let mut result = Vec::new();
    for (header, body) in manifest_sections(manifest) {
        let Some(section_kind) = dependency_section_kind(header) else {
            continue;
        };
        for entry in manifest_dependency_entries(&body) {
            let kind = if entry.optional {
                DependencyKind::Optional
            } else {
                section_kind
            };
            result.push((entry.resolved_name, kind));
        }
    }
    result
}

fn read_to_string(path: &Path) -> io::Result<Option<String>> {
    match fs::read_to_string(path) {
        Ok(text) => Ok(Some(text)),
        Err(error) if error.kind() == ErrorKind::NotFound => Ok(None),
        Err(error) => Err(error),
    }
}

/// Classifies a resolved package's source (`.atlas/contracts/DEPENDENCY-CENSUS.md#dependency-identity`).
/// `Cargo.lock` alone cannot distinguish a workspace member from an external path dependency --
/// both have no `source` field -- so the caller must also know the real workspace-member
/// package-name set. A `source` field present but matching neither recognized prefix is `Other`,
/// never silently folded into `Registry`.
fn classify_source_kind(source: Option<&str>, is_workspace_member: bool) -> DependencySourceKind {
    match source {
        None if is_workspace_member => DependencySourceKind::WorkspaceMember,
        None => DependencySourceKind::Path,
        Some(source) if source.starts_with("registry+") => DependencySourceKind::Registry,
        Some(source) if source.starts_with("git+") => DependencySourceKind::Vcs,
        Some(_) => DependencySourceKind::Other,
    }
}

/// Censuses `root`'s Cargo dependency closure: `Cargo.lock` (the full resolved transitive graph)
/// plus each workspace member's own `Cargo.toml` (for real, evidenced `DependencyKind`).
///
/// Returns `Ok(None)` when `root` has no `Cargo.lock` at all (not a Cargo workspace) -- the caller
/// is responsible for representing that as `DependencyClosureState::NotApplicable`, never as a
/// fabricated empty-but-closed report (`.atlas/contracts/DEPENDENCY-CENSUS.md#implementation-status`).
///
/// Scope note: workspace-member discovery requires a `[workspace] members = [...]` array in the
/// root manifest; a single, non-workspace root crate (`[package]` with no `[workspace]` at all) is
/// not yet a recognized shape -- out of scope for this wave, since Atlas's own self-census (the
/// only real corpus this bootstrap is proven against) is always a workspace.
pub fn census_cargo_workspace(root: &Path) -> io::Result<Option<DependencyClosureReport>> {
    let Some(lock_text) = read_to_string(&root.join("Cargo.lock"))? else {
        return Ok(None);
    };
    let packages = parse_cargo_lock(&lock_text);

    let mut unsupported_constructs = Vec::new();
    let mut kinds_by_consumer: BTreeMap<String, Vec<(String, DependencyKind)>> = BTreeMap::new();
    let mut evidence_by_consumer: BTreeMap<String, String> = BTreeMap::new();
    let mut workspace_member_names: BTreeSet<String> = BTreeSet::new();
    if let Some(root_manifest) = read_to_string(&root.join("Cargo.toml"))? {
        let (members, members_unsupported) = workspace_members(&root_manifest);
        if members_unsupported {
            unsupported_constructs
                .push("Cargo.toml: multi-line workspace.members array is not parsed".to_owned());
        }
        for member in members {
            let manifest_path = root.join(&member).join("Cargo.toml");
            let relative_manifest_path = format!("{member}/Cargo.toml");
            if let Some(member_manifest) = read_to_string(&manifest_path)? {
                // The consumer's own package name (from its `[package] name = "..."`), not its
                // workspace-relative directory name -- these differ for `apps/cli`, whose package
                // is named `atlas-cli`.
                let consumer_name = member_manifest
                    .lines()
                    .find_map(|line| quoted_field(line.trim(), "name"))
                    .unwrap_or_else(|| member.clone());
                workspace_member_names.insert(consumer_name.clone());
                kinds_by_consumer.insert(
                    consumer_name.clone(),
                    manifest_dependency_kinds(&member_manifest),
                );
                evidence_by_consumer.insert(consumer_name, relative_manifest_path);
            }
        }
    }

    let mut by_name: BTreeMap<&str, Vec<&LockPackage>> = BTreeMap::new();
    for package in &packages {
        by_name
            .entry(package.name.as_str())
            .or_default()
            .push(package);
    }

    let mut edges = Vec::new();
    let mut dangling_references = Vec::new();
    for package in &packages {
        let consumer_kinds = kinds_by_consumer.get(&package.name);
        let consumer_evidence = evidence_by_consumer
            .get(&package.name)
            .cloned()
            .unwrap_or_else(|| "Cargo.lock".to_owned());
        for dependency_ref in &package.dependencies {
            let dependency_name = &dependency_ref.name;
            let Some(candidates) = by_name.get(dependency_name.as_str()) else {
                dangling_references.push(format!("{} -> {dependency_name}", package.name));
                continue;
            };
            let provider_package = match (candidates.as_slice(), &dependency_ref.version) {
                ([single], _) => *single,
                (_, Some(version)) => {
                    match candidates.iter().find(|p| &p.version == version) {
                        Some(matched) => *matched,
                        None => {
                            // Cargo.lock's own disambiguated entry names a resolved version this
                            // lockfile has no matching `[[package]]` block for -- a real dangling
                            // reference, not an unresolved ambiguity.
                            dangling_references.push(format!(
                                "{} -> {dependency_name} {version} (no matching resolved version among {} candidates)",
                                package.name,
                                candidates.len()
                            ));
                            continue;
                        }
                    }
                }
                (_, None) => {
                    // Multiple resolved versions share this name and the lockfile entry carries no
                    // disambiguating version suffix -- real Cargo.lock output always disambiguates
                    // in this situation, so this is an adversarial/malformed-input case, reported
                    // rather than guessed.
                    dangling_references.push(format!(
                        "{} -> {dependency_name} (ambiguous: {} candidates, no disambiguating version in lockfile entry)",
                        package.name,
                        candidates.len()
                    ));
                    continue;
                }
            };
            let source_kind = classify_source_kind(
                provider_package.source.as_deref(),
                workspace_member_names.contains(&provider_package.name),
            );
            let kind = consumer_kinds.and_then(|declared| {
                declared
                    .iter()
                    .find(|(name, _)| name == dependency_name)
                    .map(|(_, kind)| *kind)
            });
            let evidence_path = if kind.is_some() {
                consumer_evidence.clone()
            } else {
                "Cargo.lock".to_owned()
            };
            edges.push(DependencyEdge {
                consumer: package.name.clone(),
                provider: DependencyIdentity {
                    ecosystem: DependencyEcosystem::Cargo,
                    name: provider_package.name.clone(),
                    version: provider_package.version.clone(),
                    source_kind,
                    source_locator: provider_package.source.clone(),
                    checksum: provider_package.checksum.clone(),
                },
                kind,
                evidence_path,
            });
        }
    }
    edges.sort();
    dangling_references.sort();
    dangling_references.dedup();

    let mut instance_keys: Vec<String> = edges
        .iter()
        .map(|edge| edge.provider.identity_key())
        .collect();
    instance_keys.sort();
    instance_keys.dedup();

    // `.atlas/contracts/DEPENDENCY-CENSUS.md#implementation-status`: a present Cargo.lock that
    // parsed to zero [[package]] entries is evidence of a malformed/truncated lockfile, not a
    // verified empty project -- real Cargo output always lists at least the workspace's own
    // member packages. Distinct from `Closed` with zero edges (real packages, genuinely no
    // dependencies), which this state model treats as a real, verified answer.
    let state = if packages.is_empty() {
        DependencyClosureState::Blocked
    } else if !dangling_references.is_empty() || !unsupported_constructs.is_empty() {
        DependencyClosureState::Partial
    } else {
        DependencyClosureState::Closed
    };

    Ok(Some(DependencyClosureReport {
        schema: "atlas.dependency-closure-report.v2".into(),
        ecosystem: DependencyEcosystem::Cargo,
        root: root.to_string_lossy().into_owned(),
        state,
        edges_total: edges.len(),
        instances_total: instance_keys.len(),
        edges,
        dangling_references,
        unsupported_constructs,
        dynamic_obligations: DynamicDependencyObligation::ALL.to_vec(),
    }))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dep_ref(name: &str) -> LockDependencyRef {
        LockDependencyRef {
            name: name.to_owned(),
            version: None,
        }
    }

    // --- 1. Cargo.lock parsing -----------------------------------------------------------------

    const LOCK_FIXTURE: &str = r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "core",
 "syn",
]

[[package]]
name = "core"
version = "0.1.0"

[[package]]
name = "syn"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeef"
dependencies = [
 "unicode-ident",
]

[[package]]
name = "unicode-ident"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cafef00d"
"#;

    #[test]
    fn parses_every_package_block() {
        let packages = parse_cargo_lock(LOCK_FIXTURE);
        assert_eq!(packages.len(), 4);
        let syn = packages.iter().find(|p| p.name == "syn").unwrap();
        assert_eq!(syn.version, "2.0.0");
        assert_eq!(
            syn.source.as_deref(),
            Some("registry+https://github.com/rust-lang/crates.io-index")
        );
        assert_eq!(syn.checksum.as_deref(), Some("deadbeef"));
        assert_eq!(syn.dependencies, vec![dep_ref("unicode-ident")]);
    }

    #[test]
    fn workspace_member_packages_have_no_source() {
        let packages = parse_cargo_lock(LOCK_FIXTURE);
        let core = packages.iter().find(|p| p.name == "core").unwrap();
        assert!(core.source.is_none());
        assert!(core.checksum.is_none());
    }

    #[test]
    fn multi_line_dependency_array_is_parsed() {
        let packages = parse_cargo_lock(LOCK_FIXTURE);
        let adapter = packages.iter().find(|p| p.name == "adapter").unwrap();
        assert_eq!(adapter.dependencies, vec![dep_ref("core"), dep_ref("syn")]);
    }

    #[test]
    fn single_line_dependency_array_is_parsed() {
        let fixture = r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = ["core", "syn"]
"#;
        let packages = parse_cargo_lock(fixture);
        assert_eq!(
            packages[0].dependencies,
            vec![dep_ref("core"), dep_ref("syn")]
        );
    }

    #[test]
    fn disambiguated_dependency_array_entry_carries_its_resolved_version() {
        let fixture = r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "syn 2.0.0",
]
"#;
        let packages = parse_cargo_lock(fixture);
        assert_eq!(
            packages[0].dependencies,
            vec![LockDependencyRef {
                name: "syn".to_owned(),
                version: Some("2.0.0".to_owned()),
            }]
        );
    }

    // --- 2. Cargo.toml manifest dependency-table parsing ----------------------------------------

    #[test]
    fn plain_dependencies_table_is_recognized_as_runtime() {
        let manifest = r#"
[package]
name = "adapter"

[dependencies]
atlas_core = { package = "core", path = "../core" }
serde = { workspace = true }
syn = { version = "3.0.6", features = ["full"] }
"#;
        let kinds = manifest_dependency_kinds(manifest);
        assert_eq!(
            kinds,
            vec![
                ("core".to_owned(), DependencyKind::Runtime),
                ("serde".to_owned(), DependencyKind::Runtime),
                ("syn".to_owned(), DependencyKind::Runtime),
            ]
        );
    }

    #[test]
    fn package_rename_resolves_to_the_actual_crate_name() {
        let manifest = r#"
[dependencies]
atlas_core = { package = "core", path = "../core" }
"#;
        let kinds = manifest_dependency_kinds(manifest);
        assert_eq!(kinds, vec![("core".to_owned(), DependencyKind::Runtime)]);
    }

    #[test]
    fn dev_and_build_dependency_tables_are_distinguished_from_plain_dependencies() {
        let manifest = r#"
[dependencies]
serde = "1"

[dev-dependencies]
proptest = "1"

[build-dependencies]
cc = "1"
"#;
        let kinds = manifest_dependency_kinds(manifest);
        assert_eq!(
            kinds,
            vec![
                ("serde".to_owned(), DependencyKind::Runtime),
                ("proptest".to_owned(), DependencyKind::Dev),
                ("cc".to_owned(), DependencyKind::Build),
            ]
        );
    }

    #[test]
    fn dotted_workspace_key_resolves_to_its_bare_crate_name() {
        let manifest = "[dependencies]\nserde.workspace = true\n";
        let kinds = manifest_dependency_kinds(manifest);
        assert_eq!(kinds, vec![("serde".to_owned(), DependencyKind::Runtime)]);
    }

    #[test]
    fn optional_true_classifies_the_dependency_as_optional_regardless_of_its_table() {
        let manifest = r#"
[dependencies]
serde = "1"
extra = { version = "1", optional = true }

[dev-dependencies]
also-extra = { version = "1", optional = true }
"#;
        let kinds = manifest_dependency_kinds(manifest);
        assert_eq!(
            kinds,
            vec![
                ("serde".to_owned(), DependencyKind::Runtime),
                ("extra".to_owned(), DependencyKind::Optional),
                ("also-extra".to_owned(), DependencyKind::Optional),
            ]
        );
    }

    #[test]
    fn optional_false_is_not_classified_as_optional() {
        let manifest = r#"
[dependencies]
serde = { version = "1", optional = false }
"#;
        let kinds = manifest_dependency_kinds(manifest);
        assert_eq!(kinds, vec![("serde".to_owned(), DependencyKind::Runtime)]);
    }

    #[test]
    fn target_conditional_dependency_tables_are_classified_as_target_conditional() {
        let manifest = r#"
[dependencies]
serde = "1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dev-dependencies]
winapi = "0.3"
"#;
        let kinds = manifest_dependency_kinds(manifest);
        assert_eq!(
            kinds,
            vec![
                ("serde".to_owned(), DependencyKind::Runtime),
                ("libc".to_owned(), DependencyKind::TargetConditional),
                ("winapi".to_owned(), DependencyKind::TargetConditional),
            ]
        );
    }

    #[test]
    fn a_multiline_inline_table_dependency_entry_is_still_read_correctly() {
        // Without joining continuation lines, `optional = true` here would be invisible (only
        // `foo = { version = "1",` is on the entry's own first line), silently misclassifying a
        // real optional dependency as Runtime.
        let manifest = "[dependencies]\nfoo = {\n    version = \"1\",\n    optional = true,\n}\n";
        let kinds = manifest_dependency_kinds(manifest);
        assert_eq!(kinds, vec![("foo".to_owned(), DependencyKind::Optional)]);
    }

    #[test]
    fn a_multiline_inline_table_rename_is_still_read_correctly() {
        let manifest =
            "[dependencies]\natlas_core = {\n    package = \"core\",\n    path = \"../core\",\n}\n";
        let kinds = manifest_dependency_kinds(manifest);
        assert_eq!(kinds, vec![("core".to_owned(), DependencyKind::Runtime)]);
    }

    #[test]
    fn a_multiline_inline_table_does_not_swallow_the_next_real_entry() {
        let manifest = "[dependencies]\nfoo = {\n    version = \"1\",\n}\nbar = \"2\"\n";
        let kinds = manifest_dependency_kinds(manifest);
        assert_eq!(
            kinds,
            vec![
                ("foo".to_owned(), DependencyKind::Runtime),
                ("bar".to_owned(), DependencyKind::Runtime),
            ]
        );
    }

    // --- 3. workspace members array --------------------------------------------------------------

    #[test]
    fn workspace_members_array_is_parsed() {
        let manifest =
            "[workspace]\nmembers = [\"core\", \"runtime\", \"adapter\", \"apps/cli\"]\n";
        assert_eq!(
            workspace_members(manifest),
            (
                vec![
                    "core".to_owned(),
                    "runtime".to_owned(),
                    "adapter".to_owned(),
                    "apps/cli".to_owned(),
                ],
                false,
            )
        );
    }

    #[test]
    fn multiline_workspace_members_is_detected_as_unsupported_not_silently_empty() {
        let manifest = "[workspace]\nmembers = [\n    \"core\",\n    \"adapter\",\n]\n";
        assert_eq!(workspace_members(manifest), (Vec::new(), true));
    }

    #[test]
    fn absent_workspace_members_is_not_flagged_unsupported() {
        let manifest = "[package]\nname = \"solo\"\n";
        assert_eq!(workspace_members(manifest), (Vec::new(), false));
    }

    // --- 4. end-to-end census against a synthetic workspace on disk ----------------------------

    fn write(path: &Path, content: &str) {
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, content).unwrap();
    }

    #[test]
    fn end_to_end_census_produces_a_closed_report_with_evidenced_kinds() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-1"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.toml"),
            "[workspace]\nmembers = [\"core\", \"adapter\"]\n",
        );
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "core",
 "syn",
]

[[package]]
name = "core"
version = "0.1.0"

[[package]]
name = "syn"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeef"
"#,
        );
        write(&dir.join("core/Cargo.toml"), "[package]\nname = \"core\"\n");
        write(
            &dir.join("adapter/Cargo.toml"),
            "[package]\nname = \"adapter\"\n\n[dependencies]\natlas_core = { package = \"core\", path = \"../core\" }\nsyn = \"2.0.0\"\n",
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert!(report.is_closed());
        assert_eq!(report.edges_total, 2);
        assert_eq!(report.instances_total, 2);

        let core_edge = report
            .edges
            .iter()
            .find(|edge| edge.provider.name == "core")
            .unwrap();
        assert_eq!(core_edge.consumer, "adapter");
        assert_eq!(core_edge.kind, Some(DependencyKind::Runtime));
        assert_eq!(core_edge.evidence_path, "adapter/Cargo.toml");
        assert_eq!(
            core_edge.provider.source_kind,
            DependencySourceKind::WorkspaceMember
        );

        let syn_edge = report
            .edges
            .iter()
            .find(|edge| edge.provider.name == "syn")
            .unwrap();
        assert_eq!(syn_edge.kind, Some(DependencyKind::Runtime));
        assert_eq!(
            syn_edge.provider.source_kind,
            DependencySourceKind::Registry
        );
        assert_eq!(syn_edge.provider.checksum.as_deref(), Some("deadbeef"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_dangling_dependency_reference_is_reported_not_dropped() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-2"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "ghost-crate",
]
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert!(!report.is_closed());
        assert_eq!(report.edges_total, 0);
        assert_eq!(
            report.dangling_references,
            vec!["adapter -> ghost-crate".to_owned()]
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_root_with_no_cargo_lock_is_not_a_cargo_workspace() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-3"
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        assert!(census_cargo_workspace(&dir).unwrap().is_none());

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_transitive_edge_between_two_external_packages_has_no_guessed_kind() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-4"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "syn"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeef"
dependencies = [
 "unicode-ident",
]

[[package]]
name = "unicode-ident"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cafef00d"
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert_eq!(report.edges_total, 1);
        assert_eq!(report.edges[0].kind, None);
        assert_eq!(report.edges[0].evidence_path, "Cargo.lock");

        let _ = fs::remove_dir_all(&dir);
    }

    // --- 4b. same-name, multiple-resolved-version disambiguation --------------------------------

    #[test]
    fn a_disambiguated_lockfile_entry_resolves_to_the_matching_version_not_an_ambiguity() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-5"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "syn 2.0.0",
]

[[package]]
name = "syn"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "old"

[[package]]
name = "syn"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "new"
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert!(
            report.is_closed(),
            "a real disambiguated lockfile entry must not be reported as a dangling/ambiguous reference: {:?}",
            report.dangling_references
        );
        assert_eq!(report.edges_total, 1);
        assert_eq!(report.edges[0].provider.version, "2.0.0");
        assert_eq!(report.edges[0].provider.checksum.as_deref(), Some("new"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_disambiguated_lockfile_entry_naming_a_version_with_no_matching_package_is_a_dangling_reference()
     {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-6"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "syn 3.0.0",
]

[[package]]
name = "syn"
version = "1.0.0"

[[package]]
name = "syn"
version = "2.0.0"
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert!(!report.is_closed());
        assert_eq!(report.edges_total, 0);
        assert_eq!(
            report.dangling_references,
            vec![
                "adapter -> syn 3.0.0 (no matching resolved version among 2 candidates)".to_owned()
            ]
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn an_ambiguous_entry_with_no_disambiguating_version_is_reported_not_guessed() {
        // Real Cargo.lock output always disambiguates when more than one resolved version of a
        // name exists, so this exercises the adversarial/malformed-input case: a hand-edited or
        // corrupted lockfile whose dependency entry carries no version suffix at all.
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-7"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "syn",
]

[[package]]
name = "syn"
version = "1.0.0"

[[package]]
name = "syn"
version = "2.0.0"
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert!(!report.is_closed());
        assert_eq!(report.edges_total, 0);
        assert_eq!(
            report.dangling_references,
            vec![
                "adapter -> syn (ambiguous: 2 candidates, no disambiguating version in lockfile entry)"
                    .to_owned()
            ]
        );

        let _ = fs::remove_dir_all(&dir);
    }

    // --- 4c. source classification and closure-state semantics ---------------------------------

    #[test]
    fn a_git_dependency_is_classified_vcs_not_registry() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-8"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "somecrate",
]

[[package]]
name = "somecrate"
version = "0.1.0"
source = "git+https://github.com/example/somecrate?rev=abc123#abc123"
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert_eq!(
            report.edges[0].provider.source_kind,
            DependencySourceKind::Vcs
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn an_unrecognized_source_prefix_is_classified_other_not_registry() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-9"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "somecrate",
]

[[package]]
name = "somecrate"
version = "0.1.0"
source = "sparse+https://example.com/index/"
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert_eq!(
            report.edges[0].provider.source_kind,
            DependencySourceKind::Other
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_source_less_package_outside_the_known_workspace_members_is_classified_path_not_workspace_member()
     {
        // A non-workspace `path = "..."` dependency has no `source` field in Cargo.lock, exactly
        // like a real workspace member. Only cross-referencing the root manifest's own declared
        // `workspace.members` (here: only "adapter") can tell them apart.
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-10"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.toml"),
            "[workspace]\nmembers = [\"adapter\"]\n",
        );
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "sibling",
]

[[package]]
name = "sibling"
version = "0.1.0"
"#,
        );
        write(
            &dir.join("adapter/Cargo.toml"),
            "[package]\nname = \"adapter\"\n\n[dependencies]\nsibling = { path = \"../sibling\" }\n",
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        let sibling_edge = report
            .edges
            .iter()
            .find(|edge| edge.provider.name == "sibling")
            .unwrap();
        assert_eq!(
            sibling_edge.provider.source_kind,
            DependencySourceKind::Path
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_lockfile_with_zero_packages_is_blocked_not_closed() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-11"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            "# This file is automatically @generated by Cargo.\nversion = 4\n",
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert_eq!(report.state, DependencyClosureState::Blocked);
        assert!(!report.is_closed());

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_multiline_workspace_members_array_forces_partial_state_even_with_no_dangling_references() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-12"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.toml"),
            "[workspace]\nmembers = [\n    \"core\",\n]\n",
        );
        write(
            &dir.join("Cargo.lock"),
            "\n[[package]]\nname = \"core\"\nversion = \"0.1.0\"\n",
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert_eq!(report.state, DependencyClosureState::Partial);
        assert!(!report.unsupported_constructs.is_empty());
        assert!(report.dangling_references.is_empty());

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_closed_report_still_names_every_dynamic_obligation_as_unresolved() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-13"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            "\n[[package]]\nname = \"core\"\nversion = \"0.1.0\"\n",
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert_eq!(report.state, DependencyClosureState::Closed);
        assert_eq!(
            report.dynamic_obligations.len(),
            DynamicDependencyObligation::ALL.len(),
            "a resolved static graph must not imply build.rs/proc-macro/... obligations are resolved too"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    // --- 5. real self-census: Atlas's own actual Cargo.lock/Cargo.toml files -------------------

    #[test]
    fn real_self_census_of_this_repositorys_own_workspace_finds_no_dangling_references() {
        // Deliberately walks up from this crate's own manifest dir to the real workspace root,
        // so this test exercises the ACTUAL files this repository ships, not only synthetic
        // fixtures -- the "Atlas self-census" case `.atlas/contracts/DEPENDENCY-CENSUS.md`
        // requires.
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("adapter/ has a parent directory");
        let report = census_cargo_workspace(root)
            .expect("reading this repository's own Cargo.lock/Cargo.toml must not fail")
            .expect("this repository's own root has a Cargo.lock");

        assert!(
            report.is_closed(),
            "dangling references in this repository's own real lockfile: {:?}",
            report.dangling_references
        );
        assert!(report.edges_total > 0);

        // Every workspace member's own direct dependency must have an evidenced kind (read from
        // that member's own Cargo.toml), never left as an unevidenced transitive-only edge.
        for member in ["core", "adapter", "runtime", "atlas-cli"] {
            let has_evidenced_edge = report
                .edges
                .iter()
                .any(|edge| edge.consumer == member && edge.kind.is_some());
            assert!(
                has_evidenced_edge,
                "expected at least one evidenced-kind dependency edge for workspace member `{member}`"
            );
        }
    }
}
