//! Cargo dependency census: a minimal, dedicated `Cargo.lock`/`Cargo.toml` reader.
//!
//! `Cargo.lock` is machine-generated with a small, stable subset of TOML (see its own header
//! comment: "This file is automatically @generated by Cargo. It is not intended for manual
//! editing."), and each `Cargo.toml` dependency table this parser reads is a bounded, well-known
//! shape (`.atlas/contracts/DEPENDENCY-CENSUS.md`). A dedicated parser for exactly these shapes
//! avoids adding a general TOML-parsing dependency merely to bootstrap dependency census itself
//! (a new crate to census dependencies would itself immediately need census).
//!
//! Only what these two file shapes literally state is recorded. A dependency name appearing in a
//! `Cargo.lock` package's own `dependencies` list with no corresponding `[[package]]` entry is a
//! dangling reference, never silently dropped. A transitive edge between two external (non-
//! workspace) packages never gets a guessed `DependencyRole`: this parser never fetches or reads
//! an external crate's own manifest, so it cannot know which of that crate's own dependency
//! tables the edge came from.
//!
//! `DependencyRole` (which manifest table) and `DependencyActivation` (optional/target-conditional)
//! are independently evidenced facts about one edge, never collapsed into each other: a
//! `[dev-dependencies]` entry with `optional = true` keeps its `Dev` role AND its
//! `activation.optional == true`, rather than one fact silently overwriting the other.

use atlas_core::{
    DependencyActivation, DependencyClosureReport, DependencyClosureState, DependencyEcosystem,
    DependencyEdge, DependencyIdentity, DependencyRole, DependencySourceKind,
    DynamicDependencyObligation,
};
use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    io::{self, ErrorKind},
    path::Path,
};

#[derive(Debug, Clone, Default)]
struct LockPackage {
    name: String,
    version: String,
    source: Option<String>,
    checksum: Option<String>,
    dependencies: Vec<LockDependencyRef>,
}

/// One `Cargo.lock` `dependencies` array entry. Cargo emits a bare `"name"` when exactly one
/// resolved version of that name exists in the lockfile, and disambiguates with a resolved
/// version as `"name version"` (or `"name version (source)"`) whenever more than one does. The
/// `(source)` suffix, needed only when the same name *and* version resolve from two different
/// sources, is not parsed yet -- a named, documented, not-yet-exercised gap distinct from the
/// version disambiguation this type exists to carry.
#[derive(Debug, Clone, PartialEq, Eq)]
struct LockDependencyRef {
    name: String,
    version: Option<String>,
}

/// The value of `key = "..."` on `line`, if `line` is exactly that assignment.
fn quoted_field(line: &str, key: &str) -> Option<String> {
    let rest = line.strip_prefix(key)?.trim_start();
    let rest = rest.strip_prefix('=')?.trim_start();
    let inner = rest.strip_prefix('"')?.strip_suffix('"')?;
    Some(inner.to_owned())
}

/// The bare quoted string inside one `"value"` (or `"value",`) array-entry line, e.g. a
/// `workspace.members` entry. Unlike `lock_dependency_ref`, this never strips a trailing token --
/// a workspace member path has no lockfile-style version suffix to disambiguate.
fn quoted_array_string(line: &str) -> Option<String> {
    let trimmed = line.trim().trim_end_matches(',');
    let inner = trimmed.strip_prefix('"')?.strip_suffix('"')?;
    Some(inner.to_owned())
}

/// One `"name"` or disambiguated `"name version"` lockfile dependency-array entry line.
fn lock_dependency_ref(line: &str) -> Option<LockDependencyRef> {
    let inner = quoted_array_string(line)?;
    let mut tokens = inner.split_whitespace();
    let name = tokens.next()?.to_owned();
    let version = tokens.next().map(str::to_owned);
    Some(LockDependencyRef { name, version })
}

fn parse_cargo_lock(text: &str) -> Vec<LockPackage> {
    let mut packages = Vec::new();
    let mut lines = text.lines().peekable();
    while let Some(line) = lines.next() {
        if line.trim() != "[[package]]" {
            continue;
        }
        let mut package = LockPackage::default();
        while let Some(&next) = lines.peek() {
            let trimmed = next.trim();
            if trimmed.is_empty() || trimmed.starts_with('[') {
                break;
            }
            lines.next();
            if let Some(value) = quoted_field(trimmed, "name") {
                package.name = value;
            } else if let Some(value) = quoted_field(trimmed, "version") {
                package.version = value;
            } else if let Some(value) = quoted_field(trimmed, "source") {
                package.source = Some(value);
            } else if let Some(value) = quoted_field(trimmed, "checksum") {
                package.checksum = Some(value);
            } else if let Some(rest) = trimmed.strip_prefix("dependencies = [") {
                if let Some(inline) = rest.strip_suffix(']') {
                    package.dependencies =
                        inline.split(',').filter_map(lock_dependency_ref).collect();
                } else {
                    while let Some(&dep_line) = lines.peek() {
                        if dep_line.trim() == "]" {
                            lines.next();
                            break;
                        }
                        lines.next();
                        if let Some(dependency_ref) = lock_dependency_ref(dep_line) {
                            package.dependencies.push(dependency_ref);
                        }
                    }
                }
            }
        }
        packages.push(package);
    }
    packages
}

/// The declared array-of-strings value of `workspace.members` in a root `Cargo.toml`, e.g.
/// `members = ["core", "runtime", "adapter", "apps/cli"]`, plus whether a `members` key was found
/// whose value this parser could not read to completion (a multi-line array with no closing `]`
/// line -- a truncated/malformed manifest). Both the single-line array shape (Atlas's own root
/// manifest uses it) and the multi-line shape (the common real-world style -- confirmed empirically
/// against six real external Cargo workspaces up to 1,827 packages, three of which use exactly this
/// shape) are read; blank lines and `#`-comment lines inside a multi-line array are skipped, not
/// misread as members. A `members` key found but never properly closed is detected and named
/// explicitly -- distinct from "no workspace declared at all" -- rather than silently treated the
/// same as an empty/absent key, since the caller must know a real workspace exists whose full
/// member list it could not read.
fn workspace_members(root_manifest: &str) -> (Vec<String>, bool) {
    let lines: Vec<&str> = root_manifest.lines().collect();
    let mut index = 0;
    while index < lines.len() {
        let trimmed = lines[index].trim();
        if let Some(rest) = trimmed.strip_prefix("members") {
            let rest = rest.trim_start();
            if let Some(rest) = rest.strip_prefix('=') {
                let rest = rest.trim();
                if let Some(inline) = rest.strip_prefix('[').and_then(|r| r.strip_suffix(']')) {
                    return (
                        inline.split(',').filter_map(quoted_array_string).collect(),
                        false,
                    );
                }
                if rest.starts_with('[') {
                    let mut members = Vec::new();
                    let mut cursor = index + 1;
                    while cursor < lines.len() {
                        let line = lines[cursor].trim();
                        if line.starts_with(']') {
                            return (members, false);
                        }
                        if let Some(name) = quoted_array_string(line) {
                            members.push(name);
                        }
                        cursor += 1;
                    }
                    // Reached end of file with no closing `]` line -- truncated/malformed.
                    return (members, true);
                }
            }
        }
        index += 1;
    }
    (Vec::new(), false)
}

/// Expands any workspace member entry shaped like `"prefix/*"` (Cargo's own single-level
/// directory-glob member shorthand) into one entry per real subdirectory of `root.join(prefix)`
/// that contains its own `Cargo.toml` -- sorted for determinism. A non-glob entry passes through
/// unchanged. Real, common Cargo idiom: this repository's own donor corpus has multiple manifests
/// declaring a member this way (e.g. `.atlas/temporary/donors/object/Cargo.toml`'s
/// `members = ["crates/*"]`, `mold`'s `members = ["cli", "arch/*", "tests"]`). Before this fix,
/// such an entry was treated as a literal, non-existent path (`root.join("crates/*").join(
/// "Cargo.toml")` never exists on any real filesystem), silently discarding every real crate
/// underneath: no diagnostic, no `unsupported_constructs` entry, no dangling reference -- the
/// member was simply skipped when `read_to_string` returned `None`, so every dependency edge whose
/// consumer is one of those crates silently fell back to `role: None`.
///
/// Cargo itself supports arbitrarily nested glob segments and multiple `*` per pattern; this scope
/// is deliberately narrower -- exactly the single-trailing-`/*`-component shape real donor
/// manifests in this corpus use -- broadened only if real input ever demonstrates the need,
/// matching this file's evidence-before-code discipline.
fn expand_glob_members(root: &Path, members: Vec<String>) -> Vec<String> {
    let mut expanded = Vec::new();
    for member in members {
        let Some(prefix) = member.strip_suffix("/*") else {
            expanded.push(member);
            continue;
        };
        // A root `Cargo.toml` is attacker-controlled input (a census target or donor-corpus
        // manifest, never authored by this bootstrap itself): `members = ["../../../*"]` must not
        // be allowed to walk and read directories outside `root`. Uses the same lexical
        // containment predicate already relied on for manifest-declared source roots.
        if !atlas_core::declared_root_is_contained(prefix) {
            continue;
        }
        let Ok(entries) = fs::read_dir(root.join(prefix)) else {
            continue;
        };
        let mut children: Vec<String> = entries
            .filter_map(Result::ok)
            .filter(|entry| entry.path().join("Cargo.toml").is_file())
            .filter_map(|entry| entry.file_name().into_string().ok())
            .map(|name| format!("{prefix}/{name}"))
            .collect();
        children.sort();
        expanded.extend(children);
    }
    expanded
}

/// One `[dependencies]`-shaped table entry: the resolved crate name it actually names (the key
/// itself, unless the entry renames via `package = "..."`, e.g. `atlas_core = { package = "core",
/// path = "../core" }` names the crate `core`, not `atlas_core`) and whether it declares
/// `optional = true`.
struct ManifestDependencyEntry {
    resolved_name: String,
    optional: bool,
}

/// Net count of `{`/`}` in `text` -- used to detect and join an inline table value that spans
/// more than one physical line (e.g. `foo = { version = "1",\n features = ["x"] }`). Adequate for
/// this bounded shape: a Cargo dependency-table value never itself contains a literal brace inside
/// a string (versions/features never do), so counting raw characters cannot be fooled here the way
/// it could be for arbitrary TOML.
fn brace_depth(text: &str) -> i32 {
    text.chars()
        .map(|c| match c {
            '{' => 1,
            '}' => -1,
            _ => 0,
        })
        .sum()
}

fn manifest_dependency_entries(section: &str) -> Vec<ManifestDependencyEntry> {
    let mut entries = Vec::new();
    let lines: Vec<&str> = section.lines().collect();
    let mut index = 0;
    while index < lines.len() {
        let trimmed = lines[index].trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            index += 1;
            continue;
        }
        let Some(eq_pos) = trimmed.find('=') else {
            index += 1;
            continue;
        };
        let key = trimmed[..eq_pos]
            .trim()
            .split('.')
            .next()
            .unwrap_or_default()
            .trim();
        if key.is_empty() {
            index += 1;
            continue;
        }
        let mut value = trimmed[eq_pos + 1..].trim().to_owned();
        // An inline table opened here but not closed on the same line spans further physical
        // lines; join them so `quoted_field_anywhere`/`bool_field_anywhere` see the whole table,
        // not just its first fragment (a bare `package = "..."` or `optional = true` on a later
        // line would otherwise be silently missed).
        let mut depth = brace_depth(&value);
        while depth > 0 {
            index += 1;
            let Some(&next) = lines.get(index) else {
                break;
            };
            value.push(' ');
            value.push_str(next.trim());
            depth += brace_depth(next.trim());
        }
        let resolved_name =
            quoted_field_anywhere(&value, "package").unwrap_or_else(|| key.to_owned());
        let optional = bool_field_anywhere(&value, "optional").unwrap_or(false);
        entries.push(ManifestDependencyEntry {
            resolved_name,
            optional,
        });
        index += 1;
    }
    entries
}

/// Like `quoted_field`, but `key = "value"` may appear anywhere in `text` (inside a `{ ... }`
/// inline table), not only as the whole line.
fn quoted_field_anywhere(text: &str, key: &str) -> Option<String> {
    let needle = format!("{key} = \"");
    let start = text.find(&needle)? + needle.len();
    let end = text[start..].find('"')? + start;
    Some(text[start..end].to_owned())
}

/// Like `quoted_field_anywhere`, but for a bare `key = true`/`key = false` (inline-table booleans
/// are never quoted in TOML).
fn bool_field_anywhere(text: &str, key: &str) -> Option<bool> {
    if text.contains(&format!("{key} = true")) {
        Some(true)
    } else if text.contains(&format!("{key} = false")) {
        Some(false)
    } else {
        None
    }
}

/// Every top-level `[section header]` in `manifest`, paired with its body text (up to the next
/// section header or end of file).
fn manifest_sections(manifest: &str) -> Vec<(&str, String)> {
    let lines: Vec<&str> = manifest.lines().collect();
    let mut sections = Vec::new();
    let mut index = 0;
    while index < lines.len() {
        let trimmed = lines[index].trim();
        if !trimmed.starts_with('[') {
            index += 1;
            continue;
        }
        let start = index + 1;
        let end = lines[start..]
            .iter()
            .position(|line| line.trim_start().starts_with('['))
            .map(|offset| start + offset)
            .unwrap_or(lines.len());
        sections.push((trimmed, lines[start..end].join("\n")));
        index = end;
    }
    sections
}

/// Classifies a manifest section header into its `(DependencyRole, is_target_conditional)` facts,
/// if it is a dependency table at all. Role and target-conditionality are orthogonal: a bare
/// `[build-dependencies]` table is `(Build, false)`; the identical table nested under
/// `[target.'cfg(...)'.build-dependencies]` (any target-selector spelling -- the selector
/// expression itself is not yet parsed/represented, an explicit, documented gap) is `(Build,
/// true)` -- the role is preserved, never overwritten, by target-conditionality.
fn dependency_section_role(header: &str) -> Option<(DependencyRole, bool)> {
    match header {
        "[dependencies]" => Some((DependencyRole::Runtime, false)),
        "[dev-dependencies]" => Some((DependencyRole::Dev, false)),
        "[build-dependencies]" => Some((DependencyRole::Build, false)),
        _ if header.starts_with("[target.") && header.ends_with(".dependencies]") => {
            Some((DependencyRole::Runtime, true))
        }
        _ if header.starts_with("[target.") && header.ends_with(".dev-dependencies]") => {
            Some((DependencyRole::Dev, true))
        }
        _ if header.starts_with("[target.") && header.ends_with(".build-dependencies]") => {
            Some((DependencyRole::Build, true))
        }
        _ => None,
    }
}

/// Classifies a dotted single-dependency table header (`[dependencies.serde]`,
/// `[dev-dependencies.wasmtime]`, `[build-dependencies.cc]`) into its own `(crate_key,
/// DependencyRole)`, the alternative TOML spelling of one `crate = { ... }` table-array entry.
/// Real, not hypothetical: `.atlas/temporary/donors/wasmtime/Cargo.toml` declares
/// `[dev-dependencies.wasmtime]` this way. Deliberately does not recognize the target-conditional
/// combination (`[target.'cfg(...)'.dependencies.NAME]`) -- no real donor manifest in this
/// repository's own corpus uses that combined form, and guessing its shape without evidence would
/// risk fabricating a parse rule this bootstrap cannot verify; a future generation should add it
/// if and when real input demonstrates the need, matching this file's own evidence-before-code
/// discipline.
fn dotted_dependency_header(header: &str) -> Option<(&str, DependencyRole)> {
    for (prefix, role) in [
        ("[dependencies.", DependencyRole::Runtime),
        ("[dev-dependencies.", DependencyRole::Dev),
        ("[build-dependencies.", DependencyRole::Build),
    ] {
        if let Some(key) = header
            .strip_prefix(prefix)
            .and_then(|rest| rest.strip_suffix(']'))
            && !key.is_empty()
        {
            return Some((key, role));
        }
    }
    None
}

/// `(crate_name, DependencyRole, DependencyActivation)` for every dependency this manifest text
/// directly declares, across every recognized table. Role (which table) and activation
/// (optional/target-conditional) are independently evidenced and never overwrite each other: a
/// `[dev-dependencies]` entry with `optional = true` is `(Dev, {optional: true, ..})`, not
/// collapsed into an `Optional`-only fact that discards `Dev`. Neither `optional` nor
/// `target_conditional` means "active in this admitted context" -- Cargo only actually activates
/// an optional dependency when the enabling feature is selected, a fact this bootstrap does not
/// yet model as its own resolution context; here they mean only "declared" that way.
fn manifest_dependency_roles(
    manifest: &str,
) -> Vec<(String, DependencyRole, DependencyActivation)> {
    let mut result = Vec::new();
    for (header, body) in manifest_sections(manifest) {
        if let Some((role, target_conditional)) = dependency_section_role(header) {
            for entry in manifest_dependency_entries(&body) {
                let activation = DependencyActivation {
                    optional: entry.optional,
                    target_conditional,
                };
                result.push((entry.resolved_name, role, activation));
            }
            continue;
        }
        if let Some((key, role)) = dotted_dependency_header(header) {
            let resolved_name =
                quoted_field_anywhere(&body, "package").unwrap_or_else(|| key.to_owned());
            let optional = bool_field_anywhere(&body, "optional").unwrap_or(false);
            result.push((
                resolved_name,
                role,
                DependencyActivation {
                    optional,
                    target_conditional: false,
                },
            ));
        }
    }
    result
}

fn read_to_string(path: &Path) -> io::Result<Option<String>> {
    match fs::read_to_string(path) {
        Ok(text) => Ok(Some(text)),
        Err(error) if error.kind() == ErrorKind::NotFound => Ok(None),
        Err(error) => Err(error),
    }
}

/// Classifies a resolved package's source (`.atlas/contracts/DEPENDENCY-CENSUS.md#dependency-identity`).
/// `Cargo.lock` alone cannot distinguish a workspace member from an external path dependency --
/// both have no `source` field -- so the caller must also know the real workspace-member
/// package-name set. A `source` field present but matching neither recognized prefix is `Other`,
/// never silently folded into `Registry`.
fn classify_source_kind(source: Option<&str>, is_workspace_member: bool) -> DependencySourceKind {
    match source {
        None if is_workspace_member => DependencySourceKind::WorkspaceMember,
        None => DependencySourceKind::Path,
        Some(source) if source.starts_with("registry+") => DependencySourceKind::Registry,
        Some(source) if source.starts_with("git+") => DependencySourceKind::Vcs,
        Some(_) => DependencySourceKind::Other,
    }
}

/// Censuses `root`'s Cargo dependency closure: `Cargo.lock` (the full resolved transitive graph)
/// plus each workspace member's own `Cargo.toml` (for real, evidenced `DependencyRole`/
/// `DependencyActivation`).
///
/// Returns `Ok(None)` when `root` has no `Cargo.lock` at all (not a Cargo workspace) -- the caller
/// is responsible for representing that as `DependencyClosureState::NotApplicable`, never as a
/// fabricated empty-but-closed report (`.atlas/contracts/DEPENDENCY-CENSUS.md#implementation-status`).
///
/// Scope note: workspace-member discovery requires a `[workspace] members = [...]` array in the
/// root manifest; a single, non-workspace root crate (`[package]` with no `[workspace]` at all) is
/// not yet a recognized shape -- out of scope for this wave, since Atlas's own self-census (the
/// only real corpus this bootstrap is proven against) is always a workspace.
pub fn census_cargo_workspace(root: &Path) -> io::Result<Option<DependencyClosureReport>> {
    let Some(lock_text) = read_to_string(&root.join("Cargo.lock"))? else {
        return Ok(None);
    };
    let packages = parse_cargo_lock(&lock_text);

    let mut unsupported_constructs = Vec::new();
    let mut roles_by_consumer: BTreeMap<
        String,
        Vec<(String, DependencyRole, DependencyActivation)>,
    > = BTreeMap::new();
    let mut evidence_by_consumer: BTreeMap<String, String> = BTreeMap::new();
    let mut workspace_member_names: BTreeSet<String> = BTreeSet::new();
    if let Some(root_manifest) = read_to_string(&root.join("Cargo.toml"))? {
        let (members, members_unsupported) = workspace_members(&root_manifest);
        if members_unsupported {
            unsupported_constructs
                .push("Cargo.toml: multi-line workspace.members array is not parsed".to_owned());
        }
        let members = expand_glob_members(root, members);
        for member in members {
            // A plain (non-glob) `workspace.members` entry is the same attacker-controlled
            // string as a glob prefix (e.g. `members = ["../../../some/other/project"]`) and gets
            // joined onto `root` the same way -- must be rejected here too, not just for globs.
            if !atlas_core::declared_root_is_contained(&member) {
                unsupported_constructs.push(format!(
                    "Cargo.toml: workspace member \"{member}\" escapes the repository root and was skipped"
                ));
                continue;
            }
            let manifest_path = root.join(&member).join("Cargo.toml");
            let relative_manifest_path = format!("{member}/Cargo.toml");
            if let Some(member_manifest) = read_to_string(&manifest_path)? {
                // The consumer's own package name (from its `[package] name = "..."`), not its
                // workspace-relative directory name -- these differ for `apps/cli`, whose package
                // is named `atlas-cli`.
                let consumer_name = member_manifest
                    .lines()
                    .find_map(|line| quoted_field(line.trim(), "name"))
                    .unwrap_or_else(|| member.clone());
                workspace_member_names.insert(consumer_name.clone());
                roles_by_consumer.insert(
                    consumer_name.clone(),
                    manifest_dependency_roles(&member_manifest),
                );
                evidence_by_consumer.insert(consumer_name, relative_manifest_path);
            }
        }
        // A workspace root manifest MAY also declare `[package]` itself -- a real, common "mixed"
        // shape: the root crate IS one of the workspace's own binaries/libraries, and Cargo never
        // lists the root in its own `workspace.members` array (it is an implicit member). Real,
        // not hypothetical: `.atlas/temporary/donors/wasmtime/Cargo.toml` is exactly this shape
        // (`[package] name = "wasmtime-cli"` plus a `[workspace] members = [...]` array that
        // correctly never lists the root). Before this fix, such a root's own
        // `[dependencies]`/`[dev-dependencies]`/`[build-dependencies]` tables were never attributed
        // to any consumer at all -- every edge whose consumer is the root package silently fell
        // back to `role: None`, `activation: ALWAYS`, `evidence_path: "Cargo.lock"`,
        // indistinguishable from a genuine external-to-external edge this parser structurally
        // cannot evidence, even though the manifest that DOES evidence it was already sitting in
        // `root_manifest`, read moments earlier.
        if root_manifest.lines().any(|line| line.trim() == "[package]")
            && let Some(root_name) = root_manifest
                .lines()
                .find_map(|line| quoted_field(line.trim(), "name"))
        {
            workspace_member_names.insert(root_name.clone());
            roles_by_consumer.insert(root_name.clone(), manifest_dependency_roles(&root_manifest));
            evidence_by_consumer.insert(root_name, "Cargo.toml".to_owned());
        }
    }

    let mut by_name: BTreeMap<&str, Vec<&LockPackage>> = BTreeMap::new();
    for package in &packages {
        by_name
            .entry(package.name.as_str())
            .or_default()
            .push(package);
    }

    let mut edges = Vec::new();
    let mut dangling_references = Vec::new();
    for package in &packages {
        let consumer_roles = roles_by_consumer.get(&package.name);
        let consumer_evidence = evidence_by_consumer
            .get(&package.name)
            .cloned()
            .unwrap_or_else(|| "Cargo.lock".to_owned());
        for dependency_ref in &package.dependencies {
            let dependency_name = &dependency_ref.name;
            let Some(candidates) = by_name.get(dependency_name.as_str()) else {
                dangling_references.push(format!("{} -> {dependency_name}", package.name));
                continue;
            };
            let provider_package = match (candidates.as_slice(), &dependency_ref.version) {
                ([single], None) => *single,
                ([single], Some(version)) => {
                    if &single.version == version {
                        *single
                    } else {
                        // A single candidate exists but the lockfile's own dependency-array entry
                        // names a disambiguating version that doesn't match it -- the same real
                        // dangling reference the multi-candidate branch below reports, not a case
                        // to silently accept the lone candidate as if it were unversioned.
                        dangling_references.push(format!(
                            "{} -> {dependency_name} {version} (no matching resolved version among {} candidates)",
                            package.name,
                            candidates.len()
                        ));
                        continue;
                    }
                }
                (_, Some(version)) => {
                    match candidates.iter().find(|p| &p.version == version) {
                        Some(matched) => *matched,
                        None => {
                            // Cargo.lock's own disambiguated entry names a resolved version this
                            // lockfile has no matching `[[package]]` block for -- a real dangling
                            // reference, not an unresolved ambiguity.
                            dangling_references.push(format!(
                                "{} -> {dependency_name} {version} (no matching resolved version among {} candidates)",
                                package.name,
                                candidates.len()
                            ));
                            continue;
                        }
                    }
                }
                (_, None) => {
                    // Multiple resolved versions share this name and the lockfile entry carries no
                    // disambiguating version suffix -- real Cargo.lock output always disambiguates
                    // in this situation, so this is an adversarial/malformed-input case, reported
                    // rather than guessed.
                    dangling_references.push(format!(
                        "{} -> {dependency_name} (ambiguous: {} candidates, no disambiguating version in lockfile entry)",
                        package.name,
                        candidates.len()
                    ));
                    continue;
                }
            };
            let source_kind = classify_source_kind(
                provider_package.source.as_deref(),
                workspace_member_names.contains(&provider_package.name),
            );
            let declared = consumer_roles
                .and_then(|declared| declared.iter().find(|(name, _, _)| name == dependency_name));
            let role = declared.map(|(_, role, _)| *role);
            let activation = declared.map_or(DependencyActivation::ALWAYS, |(_, _, activation)| {
                *activation
            });
            let evidence_path = if role.is_some() {
                consumer_evidence.clone()
            } else {
                "Cargo.lock".to_owned()
            };
            edges.push(DependencyEdge {
                consumer: package.name.clone(),
                provider: DependencyIdentity {
                    ecosystem: DependencyEcosystem::Cargo,
                    name: provider_package.name.clone(),
                    version: provider_package.version.clone(),
                    source_kind,
                    source_locator: provider_package.source.clone(),
                    checksum: provider_package.checksum.clone(),
                },
                role,
                activation,
                evidence_path,
            });
        }
    }
    edges.sort();
    dangling_references.sort();
    dangling_references.dedup();

    let mut instance_keys: Vec<String> = edges
        .iter()
        .map(|edge| edge.provider.identity_key())
        .collect();
    instance_keys.sort();
    instance_keys.dedup();

    // `.atlas/contracts/DEPENDENCY-CENSUS.md#implementation-status`: a present Cargo.lock that
    // parsed to zero [[package]] entries is evidence of a malformed/truncated lockfile, not a
    // verified empty project -- real Cargo output always lists at least the workspace's own
    // member packages. Distinct from `Closed` with zero edges (real packages, genuinely no
    // dependencies), which this state model treats as a real, verified answer.
    let state = if packages.is_empty() {
        DependencyClosureState::Blocked
    } else if !dangling_references.is_empty() || !unsupported_constructs.is_empty() {
        DependencyClosureState::Partial
    } else {
        DependencyClosureState::Closed
    };

    Ok(Some(DependencyClosureReport {
        schema: "atlas.dependency-closure-report.v3".into(),
        ecosystem: DependencyEcosystem::Cargo,
        root: root.to_string_lossy().into_owned(),
        state,
        edges_total: edges.len(),
        instances_total: instance_keys.len(),
        edges,
        dangling_references,
        unsupported_constructs,
        dynamic_obligations: DynamicDependencyObligation::ALL.to_vec(),
    }))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dep_ref(name: &str) -> LockDependencyRef {
        LockDependencyRef {
            name: name.to_owned(),
            version: None,
        }
    }

    // --- 1. Cargo.lock parsing -----------------------------------------------------------------

    const LOCK_FIXTURE: &str = r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "core",
 "syn",
]

[[package]]
name = "core"
version = "0.1.0"

[[package]]
name = "syn"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeef"
dependencies = [
 "unicode-ident",
]

[[package]]
name = "unicode-ident"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cafef00d"
"#;

    #[test]
    fn parses_every_package_block() {
        let packages = parse_cargo_lock(LOCK_FIXTURE);
        assert_eq!(packages.len(), 4);
        let syn = packages.iter().find(|p| p.name == "syn").unwrap();
        assert_eq!(syn.version, "2.0.0");
        assert_eq!(
            syn.source.as_deref(),
            Some("registry+https://github.com/rust-lang/crates.io-index")
        );
        assert_eq!(syn.checksum.as_deref(), Some("deadbeef"));
        assert_eq!(syn.dependencies, vec![dep_ref("unicode-ident")]);
    }

    #[test]
    fn workspace_member_packages_have_no_source() {
        let packages = parse_cargo_lock(LOCK_FIXTURE);
        let core = packages.iter().find(|p| p.name == "core").unwrap();
        assert!(core.source.is_none());
        assert!(core.checksum.is_none());
    }

    #[test]
    fn multi_line_dependency_array_is_parsed() {
        let packages = parse_cargo_lock(LOCK_FIXTURE);
        let adapter = packages.iter().find(|p| p.name == "adapter").unwrap();
        assert_eq!(adapter.dependencies, vec![dep_ref("core"), dep_ref("syn")]);
    }

    #[test]
    fn single_line_dependency_array_is_parsed() {
        let fixture = r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = ["core", "syn"]
"#;
        let packages = parse_cargo_lock(fixture);
        assert_eq!(
            packages[0].dependencies,
            vec![dep_ref("core"), dep_ref("syn")]
        );
    }

    #[test]
    fn disambiguated_dependency_array_entry_carries_its_resolved_version() {
        let fixture = r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "syn 2.0.0",
]
"#;
        let packages = parse_cargo_lock(fixture);
        assert_eq!(
            packages[0].dependencies,
            vec![LockDependencyRef {
                name: "syn".to_owned(),
                version: Some("2.0.0".to_owned()),
            }]
        );
    }

    // --- 2. Cargo.toml manifest dependency-table parsing ----------------------------------------

    const ALWAYS: DependencyActivation = DependencyActivation::ALWAYS;
    const OPTIONAL: DependencyActivation = DependencyActivation {
        optional: true,
        target_conditional: false,
    };
    const TARGET_CONDITIONAL: DependencyActivation = DependencyActivation {
        optional: false,
        target_conditional: true,
    };

    #[test]
    fn plain_dependencies_table_is_recognized_as_runtime() {
        let manifest = r#"
[package]
name = "adapter"

[dependencies]
atlas_core = { package = "core", path = "../core" }
serde = { workspace = true }
syn = { version = "3.0.6", features = ["full"] }
"#;
        let roles = manifest_dependency_roles(manifest);
        assert_eq!(
            roles,
            vec![
                ("core".to_owned(), DependencyRole::Runtime, ALWAYS),
                ("serde".to_owned(), DependencyRole::Runtime, ALWAYS),
                ("syn".to_owned(), DependencyRole::Runtime, ALWAYS),
            ]
        );
    }

    #[test]
    fn package_rename_resolves_to_the_actual_crate_name() {
        let manifest = r#"
[dependencies]
atlas_core = { package = "core", path = "../core" }
"#;
        let roles = manifest_dependency_roles(manifest);
        assert_eq!(
            roles,
            vec![("core".to_owned(), DependencyRole::Runtime, ALWAYS)]
        );
    }

    #[test]
    fn dev_and_build_dependency_tables_are_distinguished_from_plain_dependencies() {
        let manifest = r#"
[dependencies]
serde = "1"

[dev-dependencies]
proptest = "1"

[build-dependencies]
cc = "1"
"#;
        let roles = manifest_dependency_roles(manifest);
        assert_eq!(
            roles,
            vec![
                ("serde".to_owned(), DependencyRole::Runtime, ALWAYS),
                ("proptest".to_owned(), DependencyRole::Dev, ALWAYS),
                ("cc".to_owned(), DependencyRole::Build, ALWAYS),
            ]
        );
    }

    #[test]
    fn dotted_workspace_key_resolves_to_its_bare_crate_name() {
        let manifest = "[dependencies]\nserde.workspace = true\n";
        let roles = manifest_dependency_roles(manifest);
        assert_eq!(
            roles,
            vec![("serde".to_owned(), DependencyRole::Runtime, ALWAYS)]
        );
    }

    #[test]
    fn dotted_single_dependency_table_is_recognized_with_its_own_role() {
        // The alternative TOML spelling of one table-array entry: `[dev-dependencies.wasmtime]`
        // means the exact same thing as `wasmtime = { ... }` inside a `[dev-dependencies]` table,
        // just with the crate name in the header instead of as a body key. Real, not hypothetical:
        // `.atlas/temporary/donors/wasmtime/Cargo.toml` declares `[dev-dependencies.wasmtime]` this
        // way. Before this fix, `manifest_sections` still split it out as its own section (since it
        // starts with `[`), but `dependency_section_role` never recognized the dotted header at
        // all, so the whole entry -- including its own `optional`/`package` facts -- silently
        // vanished from `manifest_dependency_roles`'s output.
        let manifest = r#"
[dependencies]
serde = "1"

[dev-dependencies.wasmtime-fuzz]
workspace = true
optional = true

[build-dependencies.cc]
version = "1"
"#;
        let roles = manifest_dependency_roles(manifest);
        assert_eq!(
            roles,
            vec![
                ("serde".to_owned(), DependencyRole::Runtime, ALWAYS),
                (
                    "wasmtime-fuzz".to_owned(),
                    DependencyRole::Dev,
                    DependencyActivation {
                        optional: true,
                        target_conditional: false
                    }
                ),
                ("cc".to_owned(), DependencyRole::Build, ALWAYS),
            ]
        );
    }

    #[test]
    fn dotted_single_dependency_table_honors_a_package_rename() {
        let manifest = "[dependencies.renamed]\npackage = \"real-name\"\nversion = \"1\"\n";
        let roles = manifest_dependency_roles(manifest);
        assert_eq!(
            roles,
            vec![("real-name".to_owned(), DependencyRole::Runtime, ALWAYS)]
        );
    }

    #[test]
    fn optional_true_preserves_role_and_sets_the_activation_flag_regardless_of_table() {
        // The exact regression this split type fixes: an optional dependency must keep its real
        // table role (Runtime/Dev/...), never collapse to a bare "it's optional" fact that
        // discards which table it came from.
        let manifest = r#"
[dependencies]
serde = "1"
extra = { version = "1", optional = true }

[dev-dependencies]
also-extra = { version = "1", optional = true }
"#;
        let roles = manifest_dependency_roles(manifest);
        assert_eq!(
            roles,
            vec![
                ("serde".to_owned(), DependencyRole::Runtime, ALWAYS),
                ("extra".to_owned(), DependencyRole::Runtime, OPTIONAL),
                ("also-extra".to_owned(), DependencyRole::Dev, OPTIONAL),
            ]
        );
    }

    #[test]
    fn optional_false_is_not_classified_as_optional() {
        let manifest = r#"
[dependencies]
serde = { version = "1", optional = false }
"#;
        let roles = manifest_dependency_roles(manifest);
        assert_eq!(
            roles,
            vec![("serde".to_owned(), DependencyRole::Runtime, ALWAYS)]
        );
    }

    #[test]
    fn target_conditional_dependency_tables_preserve_role_and_set_the_activation_flag() {
        // The exact regression this split type fixes: a target-conditional dev-dependency must
        // keep its Dev role, never collapse to a bare "it's target-conditional" fact.
        let manifest = r#"
[dependencies]
serde = "1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dev-dependencies]
winapi = "0.3"

[target.'cfg(windows)'.build-dependencies]
embed-resource = "1"
"#;
        let roles = manifest_dependency_roles(manifest);
        assert_eq!(
            roles,
            vec![
                ("serde".to_owned(), DependencyRole::Runtime, ALWAYS),
                (
                    "libc".to_owned(),
                    DependencyRole::Runtime,
                    TARGET_CONDITIONAL
                ),
                ("winapi".to_owned(), DependencyRole::Dev, TARGET_CONDITIONAL),
                (
                    "embed-resource".to_owned(),
                    DependencyRole::Build,
                    TARGET_CONDITIONAL
                ),
            ]
        );
    }

    #[test]
    fn optional_and_target_conditional_together_set_both_activation_flags() {
        let manifest =
            "[target.'cfg(unix)'.build-dependencies]\nfoo = { version = \"1\", optional = true }\n";
        let roles = manifest_dependency_roles(manifest);
        assert_eq!(
            roles,
            vec![(
                "foo".to_owned(),
                DependencyRole::Build,
                DependencyActivation {
                    optional: true,
                    target_conditional: true,
                }
            )]
        );
    }

    #[test]
    fn a_multiline_inline_table_dependency_entry_is_still_read_correctly() {
        // Without joining continuation lines, `optional = true` here would be invisible (only
        // `foo = { version = "1",` is on the entry's own first line), silently misclassifying a
        // real optional dependency as always-active.
        let manifest = "[dependencies]\nfoo = {\n    version = \"1\",\n    optional = true,\n}\n";
        let roles = manifest_dependency_roles(manifest);
        assert_eq!(
            roles,
            vec![("foo".to_owned(), DependencyRole::Runtime, OPTIONAL)]
        );
    }

    #[test]
    fn a_multiline_inline_table_rename_is_still_read_correctly() {
        let manifest =
            "[dependencies]\natlas_core = {\n    package = \"core\",\n    path = \"../core\",\n}\n";
        let roles = manifest_dependency_roles(manifest);
        assert_eq!(
            roles,
            vec![("core".to_owned(), DependencyRole::Runtime, ALWAYS)]
        );
    }

    #[test]
    fn a_multiline_inline_table_does_not_swallow_the_next_real_entry() {
        let manifest = "[dependencies]\nfoo = {\n    version = \"1\",\n}\nbar = \"2\"\n";
        let roles = manifest_dependency_roles(manifest);
        assert_eq!(
            roles,
            vec![
                ("foo".to_owned(), DependencyRole::Runtime, ALWAYS),
                ("bar".to_owned(), DependencyRole::Runtime, ALWAYS),
            ]
        );
    }

    // --- 3. workspace members array --------------------------------------------------------------

    #[test]
    fn workspace_members_array_is_parsed() {
        let manifest =
            "[workspace]\nmembers = [\"core\", \"runtime\", \"adapter\", \"apps/cli\"]\n";
        assert_eq!(
            workspace_members(manifest),
            (
                vec![
                    "core".to_owned(),
                    "runtime".to_owned(),
                    "adapter".to_owned(),
                    "apps/cli".to_owned(),
                ],
                false,
            )
        );
    }

    #[test]
    fn multiline_workspace_members_is_parsed_correctly() {
        // Confirmed empirically as the common real-world shape: 3 of 6 real external Cargo
        // workspaces tested (tree-sitter, wasmtime, zed, up to 1,827 packages) use exactly this
        // form, and a bracket-detection-only guard previously left every one of them `Partial`.
        let manifest = "[workspace]\nmembers = [\n    \"core\",\n    \"adapter\",\n]\n";
        assert_eq!(
            workspace_members(manifest),
            (vec!["core".to_owned(), "adapter".to_owned()], false)
        );
    }

    #[test]
    fn multiline_workspace_members_skips_blank_and_comment_lines() {
        // Real shape from a real donor manifest (zed's own Cargo.toml): blank lines and
        // `#`-comment lines appear inside the array between groups of members.
        let manifest = "[workspace]\nmembers = [\n    \"a\",\n\n    # a comment\n    \"b\",\n]\n";
        assert_eq!(
            workspace_members(manifest),
            (vec!["a".to_owned(), "b".to_owned()], false)
        );
    }

    #[test]
    fn multiline_workspace_members_with_no_closing_bracket_is_flagged_unsupported() {
        // Genuinely truncated/malformed input (no closing `]` line at all) -- distinguished from
        // the ordinary, now-supported multi-line case above.
        let manifest = "[workspace]\nmembers = [\n    \"core\",\n    \"adapter\",\n";
        let (members, unsupported) = workspace_members(manifest);
        assert_eq!(members, vec!["core".to_owned(), "adapter".to_owned()]);
        assert!(unsupported);
    }

    #[test]
    fn absent_workspace_members_is_not_flagged_unsupported() {
        let manifest = "[package]\nname = \"solo\"\n";
        assert_eq!(workspace_members(manifest), (Vec::new(), false));
    }

    // --- glob-shaped workspace members (`"crates/*"`), Cargo's own single-level directory-glob
    // member shorthand. Real, common idiom: this repository's own donor corpus has multiple
    // manifests using it (e.g. object's `members = ["crates/*"]`, mold's
    // `members = ["cli", "arch/*", "tests"]`).

    #[test]
    fn a_glob_member_expands_to_its_real_subdirectories_containing_a_cargo_toml() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}-glob-members",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("crates/a/Cargo.toml"),
            "[package]\nname = \"a\"\n",
        );
        write(
            &dir.join("crates/b/Cargo.toml"),
            "[package]\nname = \"b\"\n",
        );
        // A subdirectory with no Cargo.toml of its own must never be treated as a member.
        fs::create_dir_all(dir.join("crates/not-a-crate")).unwrap();
        // A non-member file sitting directly under the glob prefix must be ignored, not crash.
        write(&dir.join("crates/README.md"), "not a crate\n");

        let expanded = expand_glob_members(&dir, vec!["crates/*".to_owned(), "xtask".to_owned()]);
        assert_eq!(
            expanded,
            vec![
                "crates/a".to_owned(),
                "crates/b".to_owned(),
                "xtask".to_owned(),
            ]
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_glob_member_with_no_matching_directory_expands_to_nothing_not_a_crash() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}-glob-members-missing",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        let expanded = expand_glob_members(&dir, vec!["crates/*".to_owned()]);
        assert!(expanded.is_empty());
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_glob_member_prefix_that_escapes_the_root_is_never_expanded() {
        // A root Cargo.toml is attacker-controlled input (a census target or donor-corpus
        // manifest, never authored by this bootstrap itself). `members = ["../outside/*"]` must
        // not walk a real directory that happens to sit next to `root` on disk.
        let base = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}-glob-escape",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&base);
        let outside = base.join("outside");
        write(
            &outside.join("evil/Cargo.toml"),
            "[package]\nname = \"evil\"\n",
        );
        let root = base.join("root");
        fs::create_dir_all(&root).unwrap();

        let expanded = expand_glob_members(&root, vec!["../outside/*".to_owned()]);
        assert!(expanded.is_empty());

        let _ = fs::remove_dir_all(&base);
    }

    #[test]
    fn a_glob_shaped_workspace_member_attributes_dependency_roles_for_every_real_subcrate() {
        // The exact regression this fix closes: before `expand_glob_members` existed,
        // `census_cargo_workspace` treated `"crates/*"` as a literal, non-existent path, so every
        // dependency edge whose consumer was one of the real crates underneath silently fell back
        // to `role: None`, `evidence_path: "Cargo.lock"`.
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}-glob-e2e",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.toml"),
            "[workspace]\nmembers = [\"crates/*\"]\n",
        );
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "a"
version = "0.1.0"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
"#,
        );
        write(
            &dir.join("crates/a/Cargo.toml"),
            "[package]\nname = \"a\"\n\n[dependencies]\nserde = \"1\"\n",
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert!(report.unsupported_constructs.is_empty());
        let edge = report
            .edges
            .iter()
            .find(|edge| edge.consumer == "a" && edge.provider.name == "serde")
            .expect("the glob-discovered crate's own dependency edge must be present");
        assert_eq!(
            edge.role,
            Some(DependencyRole::Runtime),
            "a glob-discovered workspace member's own declared dependency role must be \
             attributed, not silently dropped just because its manifest path was never literal \
             in workspace.members"
        );
        assert_eq!(edge.evidence_path, "crates/a/Cargo.toml");

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_workspace_member_naming_a_path_outside_the_repository_root_is_rejected_not_walked() {
        // A root Cargo.toml is attacker-controlled input (a census target or donor-corpus
        // manifest, never authored by this bootstrap itself): `members = ["../outside/evil"]`
        // must not let census_cargo_workspace read and fold in a real manifest that lives outside
        // the declared repository root, e.g. a sibling checkout or the operator's own files.
        let base = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}-member-escape",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&base);
        write(
            &base.join("outside/evil/Cargo.toml"),
            "[package]\nname = \"evil\"\n\n[dependencies]\nsecret-thing = \"1\"\n",
        );
        let dir = base.join("root");
        write(
            &dir.join("Cargo.toml"),
            "[workspace]\nmembers = [\"../outside/evil\"]\n",
        );
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "root"
version = "0.1.0"
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert!(
            report
                .edges
                .iter()
                .all(|edge| edge.consumer != "evil" && edge.provider.name != "secret-thing"),
            "no edge attributed to the escaping member's manifest must ever appear"
        );
        assert_eq!(
            report.unsupported_constructs,
            vec![
                "Cargo.toml: workspace member \"../outside/evil\" escapes the repository root \
                 and was skipped"
                    .to_owned()
            ]
        );

        let _ = fs::remove_dir_all(&base);
    }

    // --- 4. end-to-end census against a synthetic workspace on disk ----------------------------

    fn write(path: &Path, content: &str) {
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, content).unwrap();
    }

    #[test]
    fn end_to_end_census_produces_a_closed_report_with_evidenced_kinds() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-1"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.toml"),
            "[workspace]\nmembers = [\"core\", \"adapter\"]\n",
        );
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "core",
 "syn",
]

[[package]]
name = "core"
version = "0.1.0"

[[package]]
name = "syn"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeef"
"#,
        );
        write(&dir.join("core/Cargo.toml"), "[package]\nname = \"core\"\n");
        write(
            &dir.join("adapter/Cargo.toml"),
            "[package]\nname = \"adapter\"\n\n[dependencies]\natlas_core = { package = \"core\", path = \"../core\" }\nsyn = \"2.0.0\"\n",
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert!(report.is_closed());
        assert_eq!(report.edges_total, 2);
        assert_eq!(report.instances_total, 2);

        let core_edge = report
            .edges
            .iter()
            .find(|edge| edge.provider.name == "core")
            .unwrap();
        assert_eq!(core_edge.consumer, "adapter");
        assert_eq!(core_edge.role, Some(DependencyRole::Runtime));
        assert_eq!(core_edge.activation, DependencyActivation::ALWAYS);
        assert_eq!(core_edge.evidence_path, "adapter/Cargo.toml");
        assert_eq!(
            core_edge.provider.source_kind,
            DependencySourceKind::WorkspaceMember
        );

        let syn_edge = report
            .edges
            .iter()
            .find(|edge| edge.provider.name == "syn")
            .unwrap();
        assert_eq!(syn_edge.role, Some(DependencyRole::Runtime));
        assert_eq!(
            syn_edge.provider.source_kind,
            DependencySourceKind::Registry
        );
        assert_eq!(syn_edge.provider.checksum.as_deref(), Some("deadbeef"));

        let _ = fs::remove_dir_all(&dir);
    }

    // --- a "mixed" root manifest (`[package]` AND `[workspace]` in the same Cargo.toml, the root
    // crate is itself a workspace member Cargo never lists in its own `members` array) must still
    // attribute the root's own declared dependency roles/activations, not silently fall back to
    // `role: None`/`evidence_path: "Cargo.lock"` for every edge whose consumer is the root package.
    // Real shape, not hypothetical: `.atlas/temporary/donors/wasmtime/Cargo.toml`.
    #[test]
    fn a_mixed_root_package_and_workspace_manifest_attributes_the_roots_own_dependency_roles() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-mixed-root"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.toml"),
            "[package]\nname = \"wasmtime-cli\"\nversion = \"1.0.0\"\n\n[workspace]\nmembers = [\"cranelift\"]\n\n[dependencies]\nwasmtime = { path = \"cranelift\" }\n\n[dev-dependencies]\ntempfile = \"3\"\n",
        );
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "wasmtime-cli"
version = "1.0.0"
dependencies = [
 "wasmtime",
 "tempfile",
]

[[package]]
name = "wasmtime"
version = "1.0.0"

[[package]]
name = "tempfile"
version = "3.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
"#,
        );
        write(
            &dir.join("cranelift/Cargo.toml"),
            "[package]\nname = \"wasmtime\"\n",
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert!(report.is_closed());
        assert!(report.unsupported_constructs.is_empty());

        let runtime_edge = report
            .edges
            .iter()
            .find(|edge| edge.consumer == "wasmtime-cli" && edge.provider.name == "wasmtime")
            .expect("the root package's own dependency edge must be present");
        assert_eq!(
            runtime_edge.role,
            Some(DependencyRole::Runtime),
            "the root manifest's own [dependencies] table must be attributed, not silently \
             dropped just because the root crate is never listed in its own workspace.members"
        );
        assert_eq!(runtime_edge.evidence_path, "Cargo.toml");

        let dev_edge = report
            .edges
            .iter()
            .find(|edge| edge.consumer == "wasmtime-cli" && edge.provider.name == "tempfile")
            .expect("the root package's own dev-dependency edge must be present");
        assert_eq!(dev_edge.role, Some(DependencyRole::Dev));
        assert_eq!(dev_edge.evidence_path, "Cargo.toml");

        let _ = fs::remove_dir_all(&dir);
    }

    // --- a pure virtual workspace root (`[workspace]` with no `[package]` at all -- Atlas's own
    // shape) must NOT invent a fake root package or attribute any dependency roles to one.
    #[test]
    fn a_pure_virtual_workspace_root_registers_no_root_package() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-virtual-root"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.toml"),
            "[workspace]\nmembers = [\"core\"]\n",
        );
        write(
            &dir.join("Cargo.lock"),
            "\n[[package]]\nname = \"core\"\nversion = \"0.1.0\"\n",
        );
        write(&dir.join("core/Cargo.toml"), "[package]\nname = \"core\"\n");

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert!(report.is_closed());
        assert_eq!(
            report.edges_total, 0,
            "a virtual workspace root has no [package] of its own, no [dependencies] table to \
             misattribute, and must not fabricate a root-package edge out of nothing"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_dangling_dependency_reference_is_reported_not_dropped() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-2"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "ghost-crate",
]
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert!(!report.is_closed());
        assert_eq!(report.edges_total, 0);
        assert_eq!(
            report.dangling_references,
            vec!["adapter -> ghost-crate".to_owned()]
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_root_with_no_cargo_lock_is_not_a_cargo_workspace() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-3"
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        assert!(census_cargo_workspace(&dir).unwrap().is_none());

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_transitive_edge_between_two_external_packages_has_no_guessed_role() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-4"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "syn"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeef"
dependencies = [
 "unicode-ident",
]

[[package]]
name = "unicode-ident"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cafef00d"
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert_eq!(report.edges_total, 1);
        assert_eq!(report.edges[0].role, None);
        assert_eq!(report.edges[0].activation, DependencyActivation::ALWAYS);
        assert_eq!(report.edges[0].evidence_path, "Cargo.lock");

        let _ = fs::remove_dir_all(&dir);
    }

    // --- 4b. same-name, multiple-resolved-version disambiguation --------------------------------

    #[test]
    fn a_disambiguated_lockfile_entry_resolves_to_the_matching_version_not_an_ambiguity() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-5"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "syn 2.0.0",
]

[[package]]
name = "syn"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "old"

[[package]]
name = "syn"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "new"
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert!(
            report.is_closed(),
            "a real disambiguated lockfile entry must not be reported as a dangling/ambiguous reference: {:?}",
            report.dangling_references
        );
        assert_eq!(report.edges_total, 1);
        assert_eq!(report.edges[0].provider.version, "2.0.0");
        assert_eq!(report.edges[0].provider.checksum.as_deref(), Some("new"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_disambiguated_lockfile_entry_naming_a_version_with_no_matching_package_is_a_dangling_reference()
     {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-6"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "syn 3.0.0",
]

[[package]]
name = "syn"
version = "1.0.0"

[[package]]
name = "syn"
version = "2.0.0"
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert!(!report.is_closed());
        assert_eq!(report.edges_total, 0);
        assert_eq!(
            report.dangling_references,
            vec![
                "adapter -> syn 3.0.0 (no matching resolved version among 2 candidates)".to_owned()
            ]
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_disambiguated_lockfile_entry_naming_a_version_with_only_one_mismatched_candidate_is_a_dangling_reference()
     {
        // A single `[[package]]` block for a name is not automatically the right provider: the
        // lockfile's own dependency-array entry can still name a disambiguating version that
        // doesn't match it (a hand-edited or merge-corrupted lockfile). This must be reported the
        // same way the multi-candidate mismatch case above is, not silently accepted as if the
        // lone candidate were unversioned.
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-6b"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "syn 1.5.0",
]

[[package]]
name = "syn"
version = "9.9.9"
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert!(!report.is_closed());
        assert_eq!(report.edges_total, 0);
        assert_eq!(
            report.dangling_references,
            vec![
                "adapter -> syn 1.5.0 (no matching resolved version among 1 candidates)".to_owned()
            ]
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn an_ambiguous_entry_with_no_disambiguating_version_is_reported_not_guessed() {
        // Real Cargo.lock output always disambiguates when more than one resolved version of a
        // name exists, so this exercises the adversarial/malformed-input case: a hand-edited or
        // corrupted lockfile whose dependency entry carries no version suffix at all.
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-7"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "syn",
]

[[package]]
name = "syn"
version = "1.0.0"

[[package]]
name = "syn"
version = "2.0.0"
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert!(!report.is_closed());
        assert_eq!(report.edges_total, 0);
        assert_eq!(
            report.dangling_references,
            vec![
                "adapter -> syn (ambiguous: 2 candidates, no disambiguating version in lockfile entry)"
                    .to_owned()
            ]
        );

        let _ = fs::remove_dir_all(&dir);
    }

    // --- 4c. source classification and closure-state semantics ---------------------------------

    #[test]
    fn a_git_dependency_is_classified_vcs_not_registry() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-8"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "somecrate",
]

[[package]]
name = "somecrate"
version = "0.1.0"
source = "git+https://github.com/example/somecrate?rev=abc123#abc123"
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert_eq!(
            report.edges[0].provider.source_kind,
            DependencySourceKind::Vcs
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn an_unrecognized_source_prefix_is_classified_other_not_registry() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-9"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "somecrate",
]

[[package]]
name = "somecrate"
version = "0.1.0"
source = "sparse+https://example.com/index/"
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert_eq!(
            report.edges[0].provider.source_kind,
            DependencySourceKind::Other
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_source_less_package_outside_the_known_workspace_members_is_classified_path_not_workspace_member()
     {
        // A non-workspace `path = "..."` dependency has no `source` field in Cargo.lock, exactly
        // like a real workspace member. Only cross-referencing the root manifest's own declared
        // `workspace.members` (here: only "adapter") can tell them apart.
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-10"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.toml"),
            "[workspace]\nmembers = [\"adapter\"]\n",
        );
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "sibling",
]

[[package]]
name = "sibling"
version = "0.1.0"
"#,
        );
        write(
            &dir.join("adapter/Cargo.toml"),
            "[package]\nname = \"adapter\"\n\n[dependencies]\nsibling = { path = \"../sibling\" }\n",
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        let sibling_edge = report
            .edges
            .iter()
            .find(|edge| edge.provider.name == "sibling")
            .unwrap();
        assert_eq!(
            sibling_edge.provider.source_kind,
            DependencySourceKind::Path
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_lockfile_with_zero_packages_is_blocked_not_closed() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-11"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            "# This file is automatically @generated by Cargo.\nversion = 4\n",
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert_eq!(report.state, DependencyClosureState::Blocked);
        assert!(!report.is_closed());

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_well_formed_multiline_workspace_members_array_is_closed_with_evidenced_kind() {
        // The common real-world shape (see multiline_workspace_members_is_parsed_correctly) must
        // reach real Closed state with real evidenced roles, not merely avoid a crash.
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-12"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.toml"),
            "[workspace]\nmembers = [\n    \"core\",\n]\n",
        );
        write(
            &dir.join("Cargo.lock"),
            "\n[[package]]\nname = \"core\"\nversion = \"0.1.0\"\n",
        );
        write(&dir.join("core/Cargo.toml"), "[package]\nname = \"core\"\n");

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert_eq!(report.state, DependencyClosureState::Closed);
        assert!(report.unsupported_constructs.is_empty());

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_truncated_multiline_workspace_members_array_forces_partial_state() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-12b"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.toml"),
            "[workspace]\nmembers = [\n    \"core\",\n",
        );
        write(
            &dir.join("Cargo.lock"),
            "\n[[package]]\nname = \"core\"\nversion = \"0.1.0\"\n",
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert_eq!(report.state, DependencyClosureState::Partial);
        assert!(!report.unsupported_constructs.is_empty());
        assert!(report.dangling_references.is_empty());

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_closed_report_still_names_every_dynamic_obligation_as_unresolved() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-13"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            "\n[[package]]\nname = \"core\"\nversion = \"0.1.0\"\n",
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert_eq!(report.state, DependencyClosureState::Closed);
        assert_eq!(
            report.dynamic_obligations.len(),
            DynamicDependencyObligation::ALL.len(),
            "a resolved static graph must not imply build.rs/proc-macro/... obligations are resolved too"
        );

        let _ = fs::remove_dir_all(&dir);
    }

    // --- 5. real self-census: Atlas's own actual Cargo.lock/Cargo.toml files -------------------

    #[test]
    fn real_self_census_of_this_repositorys_own_workspace_finds_no_dangling_references() {
        // Deliberately walks up from this crate's own manifest dir to the real workspace root,
        // so this test exercises the ACTUAL files this repository ships, not only synthetic
        // fixtures -- the "Atlas self-census" case `.atlas/contracts/DEPENDENCY-CENSUS.md`
        // requires.
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("adapter/ has a parent directory");
        let report = census_cargo_workspace(root)
            .expect("reading this repository's own Cargo.lock/Cargo.toml must not fail")
            .expect("this repository's own root has a Cargo.lock");

        assert!(
            report.is_closed(),
            "dangling references in this repository's own real lockfile: {:?}",
            report.dangling_references
        );
        assert!(report.edges_total > 0);

        // Every workspace member's own direct dependency must have an evidenced role (read from
        // that member's own Cargo.toml), never left as an unevidenced transitive-only edge.
        for member in ["core", "adapter", "runtime", "atlas-cli"] {
            let has_evidenced_edge = report
                .edges
                .iter()
                .any(|edge| edge.consumer == member && edge.role.is_some());
            assert!(
                has_evidenced_edge,
                "expected at least one evidenced-role dependency edge for workspace member `{member}`"
            );
        }
    }

    // --- 6. real-world verification: this repository's own donor corpus ------------------------

    #[test]
    fn real_census_of_every_cargo_based_donor_workspace_reaches_closed_state() {
        // Stronger verification than any synthetic fixture or Atlas's own small workspace (4
        // members, ~29 edges, no target-conditional/optional/git dependencies) can provide: every
        // real, independently-authored, large Cargo workspace in this repository's own committed
        // donor corpus (`.atlas/temporary/donors/`, not gitignored -- a permanent part of this
        // checkout), up to 1,827 packages (zed) and 10,000+ edges. Found and fixed the multi-line
        // `workspace.members` gap this way: 3 of the first 6 donors tested hit `Partial` purely
        // because of it before that fix existed. Directories are looked up dynamically and skipped
        // (not failed) if absent, so this test tolerates future donor-corpus reorganization without
        // becoming flaky -- but asserts hard against dangling references or unsupported constructs
        // for every donor it does find, and requires finding at least half of the named set so this
        // can never silently degrade into a no-op.
        let donor_root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("adapter/ has a parent directory")
            .join(".atlas/temporary/donors");
        let known_cargo_donors = [
            "ast-grep",
            "buck2",
            "c2rust",
            "crubit",
            "duumbi",
            "egglog",
            "miri",
            "mold",
            "object",
            "rust-analyzer",
            "rust",
            "tree-sitter",
            "wasm-tools",
            "wasmtime",
            "zed",
        ];

        let mut donors_found = 0usize;
        let mut total_edges = 0usize;
        for name in known_cargo_donors {
            let root = donor_root.join(name);
            let Ok(Some(report)) = census_cargo_workspace(&root) else {
                continue;
            };
            donors_found += 1;
            total_edges += report.edges_total;
            assert_eq!(
                report.state,
                DependencyClosureState::Closed,
                "donor `{name}` did not reach Closed: dangling={:?} unsupported={:?}",
                report.dangling_references,
                report.unsupported_constructs
            );
            assert!(report.dangling_references.is_empty(), "donor `{name}`");
            assert!(report.unsupported_constructs.is_empty(), "donor `{name}`");
        }

        assert!(
            donors_found >= known_cargo_donors.len() / 2,
            "expected to find at least half of the known Cargo-based donors under {}; found {donors_found}",
            donor_root.display()
        );
        assert!(
            total_edges > 1000,
            "expected substantial real edge coverage"
        );
    }

    #[test]
    fn real_donor_corpus_exercises_every_source_kind_role_and_activation_combination() {
        // Atlas's own workspace has zero git dependencies, zero non-workspace path dependencies,
        // and zero optional/target-conditional dependencies -- every classification branch for
        // those facts was previously verified only by synthetic fixtures. This repository's real
        // donor corpus genuinely exercises all of them: aggregate, real evidence that
        // classify_source_kind/manifest_dependency_roles produce non-trivial, real-world-shaped
        // output, not merely "does not crash" on real input.
        let donor_root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("adapter/ has a parent directory")
            .join(".atlas/temporary/donors");
        let known_cargo_donors = [
            "ast-grep",
            "buck2",
            "c2rust",
            "crubit",
            "duumbi",
            "egglog",
            "miri",
            "mold",
            "object",
            "rust-analyzer",
            "rust",
            "tree-sitter",
            "wasm-tools",
            "wasmtime",
            "zed",
        ];

        let mut vcs_count = 0usize;
        let mut path_count = 0usize;
        let mut dev_role_count = 0usize;
        let mut build_role_count = 0usize;
        let mut optional_count = 0usize;
        let mut target_conditional_count = 0usize;
        let mut optional_and_target_conditional_count = 0usize;

        for name in known_cargo_donors {
            let root = donor_root.join(name);
            let Ok(Some(report)) = census_cargo_workspace(&root) else {
                continue;
            };
            for edge in &report.edges {
                match edge.provider.source_kind {
                    DependencySourceKind::Vcs => vcs_count += 1,
                    DependencySourceKind::Path => path_count += 1,
                    _ => {}
                }
                match edge.role {
                    Some(DependencyRole::Dev) => dev_role_count += 1,
                    Some(DependencyRole::Build) => build_role_count += 1,
                    _ => {}
                }
                if edge.activation.optional && edge.activation.target_conditional {
                    optional_and_target_conditional_count += 1;
                } else if edge.activation.optional {
                    optional_count += 1;
                } else if edge.activation.target_conditional {
                    target_conditional_count += 1;
                }
            }
        }

        assert!(
            vcs_count > 0,
            "expected at least one real git dependency across the donor corpus"
        );
        assert!(
            path_count > 0,
            "expected at least one real non-workspace path dependency across the donor corpus"
        );
        assert!(
            dev_role_count > 0,
            "expected at least one real Dev-role edge"
        );
        assert!(
            build_role_count > 0,
            "expected at least one real Build-role edge"
        );
        assert!(
            optional_count > 0,
            "expected at least one real optional-only edge"
        );
        assert!(
            target_conditional_count > 0,
            "expected at least one real target-conditional-only edge"
        );
        assert!(
            optional_and_target_conditional_count > 0,
            "expected at least one real edge that is BOTH optional and target-conditional -- the \
             exact combination the DependencyRole/DependencyActivation split exists to represent"
        );
    }

    // --- 7. real-world verification of the mixed root-package-and-workspace fix ------------------

    #[test]
    fn real_wasmtime_donor_root_package_dependencies_are_evidenced_not_dropped() {
        // `wasmtime`'s own root Cargo.toml declares BOTH `[package] name = "wasmtime-cli"` and
        // `[workspace] members = [...]` (which, correctly, never lists the root itself -- Cargo
        // treats it as an implicit member). Before the mixed-root-manifest fix, every one of
        // `wasmtime-cli`'s own ~30 real `[dependencies]`/`[dev-dependencies]` entries silently fell
        // back to `role: None`, `evidence_path: "Cargo.lock"` -- this test locks the fix in against
        // this repository's own real, committed donor corpus, not only the synthetic fixture in
        // `a_mixed_root_package_and_workspace_manifest_attributes_the_roots_own_dependency_roles`.
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("adapter/ has a parent directory")
            .join(".atlas/temporary/donors/wasmtime");
        let Ok(Some(report)) = census_cargo_workspace(&root) else {
            // Tolerate donor-corpus reorganization the same way the other real-donor tests do --
            // this test only strengthens the claim when wasmtime is present, it never requires it.
            return;
        };
        let root_edges: Vec<_> = report
            .edges
            .iter()
            .filter(|edge| edge.consumer == "wasmtime-cli")
            .collect();
        assert!(
            !root_edges.is_empty(),
            "expected wasmtime-cli's own Cargo.lock entry to produce dependency edges"
        );
        assert!(
            root_edges.iter().any(|edge| edge.role.is_some()),
            "wasmtime-cli's own root [dependencies]/[dev-dependencies] tables must be attributed \
             a real role, not silently dropped just because the root crate is never listed in its \
             own workspace.members array"
        );
        assert!(
            root_edges
                .iter()
                .any(|edge| edge.evidence_path == "Cargo.toml"),
            "an evidenced root-package edge must cite the root manifest itself, not fall back to \
             the coarser Cargo.lock evidence path"
        );
    }

    // --- 8. real-world verification of the glob-shaped workspace member fix -----------------------

    #[test]
    fn real_object_donor_glob_members_are_evidenced_not_dropped() {
        // `object`'s own root Cargo.toml declares `[workspace] members = ["crates/*"]` -- Cargo's
        // single-level directory-glob member shorthand. Before the glob-expansion fix, every real
        // crate under `crates/` was invisible to `workspace_members` (a literal, non-existent
        // `crates/*/Cargo.toml` path), so every dependency edge whose consumer was one of those
        // crates silently fell back to `role: None`.
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("adapter/ has a parent directory")
            .join(".atlas/temporary/donors/object");
        let Ok(Some(report)) = census_cargo_workspace(&root) else {
            // Tolerate donor-corpus reorganization the same way the other real-donor tests do.
            return;
        };
        assert!(
            report.unsupported_constructs.is_empty(),
            "expected the glob member array to parse cleanly: {:?}",
            report.unsupported_constructs
        );
        let evidenced_edges = report.edges.iter().filter(|e| e.role.is_some()).count();
        assert!(
            evidenced_edges > 10,
            "expected substantial evidenced-role coverage now that crates/* is expanded to its \
             real subcrates, not just the handful of top-level (non-glob) members; got {evidenced_edges}"
        );
    }
}
