//! Cargo dependency census: a minimal, dedicated `Cargo.lock`/`Cargo.toml` reader.
//!
//! `Cargo.lock` is machine-generated with a small, stable subset of TOML (see its own header
//! comment: "This file is automatically @generated by Cargo. It is not intended for manual
//! editing."), and each `Cargo.toml` dependency table this parser reads is a bounded, well-known
//! shape (`.atlas/contracts/DEPENDENCY-CENSUS.md`). A dedicated parser for exactly these shapes
//! avoids adding a general TOML-parsing dependency merely to bootstrap dependency census itself
//! (a new crate to census dependencies would itself immediately need census).
//!
//! Only what these two file shapes literally state is recorded. A dependency name appearing in a
//! `Cargo.lock` package's own `dependencies` list with no corresponding `[[package]]` entry is a
//! dangling reference, never silently dropped. A transitive edge between two external (non-
//! workspace) packages never gets a guessed `DependencyKind`: this parser never fetches or reads
//! an external crate's own manifest, so it cannot know which of that crate's own dependency
//! tables the edge came from.

use atlas_core::{
    DependencyClosureReport, DependencyEcosystem, DependencyEdge, DependencyIdentity,
    DependencyKind, DependencySourceKind,
};
use std::{
    collections::BTreeMap,
    fs,
    io::{self, ErrorKind},
    path::Path,
};

#[derive(Debug, Clone, Default)]
struct LockPackage {
    name: String,
    version: String,
    source: Option<String>,
    checksum: Option<String>,
    dependencies: Vec<String>,
}

/// The value of `key = "..."` on `line`, if `line` is exactly that assignment.
fn quoted_field(line: &str, key: &str) -> Option<String> {
    let rest = line.strip_prefix(key)?.trim_start();
    let rest = rest.strip_prefix('=')?.trim_start();
    let inner = rest.strip_prefix('"')?.strip_suffix('"')?;
    Some(inner.to_owned())
}

/// The bare name inside one `"name"` (or `"name",`) lockfile dependency-array entry line.
fn dependency_array_entry(line: &str) -> Option<String> {
    let trimmed = line.trim().trim_end_matches(',');
    let inner = trimmed.strip_prefix('"')?.strip_suffix('"')?;
    // Cargo.lock disambiguates same-named packages at different resolved versions as
    // `"name version"` or `"name version (source)"`. This parser only reads the bare name; see
    // the module/report doc comments for how a resulting ambiguous match is reported rather than
    // guessed.
    Some(inner.split_whitespace().next().unwrap_or(inner).to_owned())
}

fn parse_cargo_lock(text: &str) -> Vec<LockPackage> {
    let mut packages = Vec::new();
    let mut lines = text.lines().peekable();
    while let Some(line) = lines.next() {
        if line.trim() != "[[package]]" {
            continue;
        }
        let mut package = LockPackage::default();
        while let Some(&next) = lines.peek() {
            let trimmed = next.trim();
            if trimmed.is_empty() || trimmed.starts_with('[') {
                break;
            }
            lines.next();
            if let Some(value) = quoted_field(trimmed, "name") {
                package.name = value;
            } else if let Some(value) = quoted_field(trimmed, "version") {
                package.version = value;
            } else if let Some(value) = quoted_field(trimmed, "source") {
                package.source = Some(value);
            } else if let Some(value) = quoted_field(trimmed, "checksum") {
                package.checksum = Some(value);
            } else if let Some(rest) = trimmed.strip_prefix("dependencies = [") {
                if let Some(inline) = rest.strip_suffix(']') {
                    package.dependencies = inline
                        .split(',')
                        .filter_map(dependency_array_entry)
                        .collect();
                } else {
                    while let Some(&dep_line) = lines.peek() {
                        if dep_line.trim() == "]" {
                            lines.next();
                            break;
                        }
                        lines.next();
                        if let Some(name) = dependency_array_entry(dep_line) {
                            package.dependencies.push(name);
                        }
                    }
                }
            }
        }
        packages.push(package);
    }
    packages
}

/// The declared array-of-strings value of `workspace.members` in a root `Cargo.toml`, e.g.
/// `members = ["core", "runtime", "adapter", "apps/cli"]`. Only the single-line array shape is
/// read (Atlas's own root manifest uses it); a multi-line `members = [` array is treated the same
/// way `dependencies` arrays are in `parse_cargo_lock`, for the same reason -- not yet needed by
/// any manifest this parser actually reads, so left as an explicit, documented gap rather than
/// guessed at.
fn workspace_members(root_manifest: &str) -> Vec<String> {
    for line in root_manifest.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("members") {
            let rest = rest.trim_start();
            if let Some(rest) = rest.strip_prefix('=') {
                let rest = rest.trim();
                if let Some(inline) = rest.strip_prefix('[').and_then(|r| r.strip_suffix(']')) {
                    return inline
                        .split(',')
                        .filter_map(dependency_array_entry)
                        .collect();
                }
            }
        }
    }
    Vec::new()
}

/// One `[dependencies]`/`[dev-dependencies]`/`[build-dependencies]` table entry: the manifest key
/// (before any `.workspace`/inline-table suffix) and the resolved crate name it actually names
/// (the key itself, unless the entry renames via `package = "..."`, e.g. `atlas_core = { package
/// = "core", path = "../core" }` names the crate `core`, not `atlas_core`).
fn manifest_dependency_entries(section: &str) -> Vec<(String, String)> {
    let mut entries = Vec::new();
    for line in section.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        let Some(eq_pos) = trimmed.find('=') else {
            continue;
        };
        let key = trimmed[..eq_pos]
            .trim()
            .split('.')
            .next()
            .unwrap_or_default()
            .trim();
        if key.is_empty() {
            continue;
        }
        let value = trimmed[eq_pos + 1..].trim();
        let resolved = quoted_field_anywhere(value, "package").unwrap_or_else(|| key.to_owned());
        entries.push((key.to_owned(), resolved));
    }
    entries
}

/// Like `quoted_field`, but `key = "value"` may appear anywhere in `text` (inside a `{ ... }`
/// inline table), not only as the whole line.
fn quoted_field_anywhere(text: &str, key: &str) -> Option<String> {
    let needle = format!("{key} = \"");
    let start = text.find(&needle)? + needle.len();
    let end = text[start..].find('"')? + start;
    Some(text[start..end].to_owned())
}

/// `(dependency table header, DependencyKind)` pairs this parser recognizes.
const DEPENDENCY_SECTIONS: &[(&str, DependencyKind)] = &[
    ("[dependencies]", DependencyKind::Runtime),
    ("[dev-dependencies]", DependencyKind::Dev),
    ("[build-dependencies]", DependencyKind::Build),
];

/// `(crate_name, DependencyKind)` for every dependency this manifest text directly declares,
/// across every recognized table.
fn manifest_dependency_kinds(manifest: &str) -> Vec<(String, DependencyKind)> {
    let mut result = Vec::new();
    let lines: Vec<&str> = manifest.lines().collect();
    for &(header, kind) in DEPENDENCY_SECTIONS {
        let Some(start) = lines.iter().position(|line| line.trim() == header) else {
            continue;
        };
        let end = lines[start + 1..]
            .iter()
            .position(|line| line.trim_start().starts_with('['))
            .map(|offset| start + 1 + offset)
            .unwrap_or(lines.len());
        let section = lines[start + 1..end].join("\n");
        for (_, resolved_name) in manifest_dependency_entries(&section) {
            result.push((resolved_name, kind));
        }
    }
    result
}

fn read_to_string(path: &Path) -> io::Result<Option<String>> {
    match fs::read_to_string(path) {
        Ok(text) => Ok(Some(text)),
        Err(error) if error.kind() == ErrorKind::NotFound => Ok(None),
        Err(error) => Err(error),
    }
}

/// Censuses `root`'s Cargo dependency closure: `Cargo.lock` (the full resolved transitive graph)
/// plus each workspace member's own `Cargo.toml` (for real, evidenced `DependencyKind`).
///
/// Returns `Ok(None)` when `root` has no `Cargo.lock` at all (not a Cargo workspace) -- distinct
/// from a present-but-empty closure, which `Ok(Some(report))` with `edges_total == 0` represents.
pub fn census_cargo_workspace(root: &Path) -> io::Result<Option<DependencyClosureReport>> {
    let Some(lock_text) = read_to_string(&root.join("Cargo.lock"))? else {
        return Ok(None);
    };
    let packages = parse_cargo_lock(&lock_text);

    let mut kinds_by_consumer: BTreeMap<String, Vec<(String, DependencyKind)>> = BTreeMap::new();
    let mut evidence_by_consumer: BTreeMap<String, String> = BTreeMap::new();
    if let Some(root_manifest) = read_to_string(&root.join("Cargo.toml"))? {
        for member in workspace_members(&root_manifest) {
            let manifest_path = root.join(&member).join("Cargo.toml");
            let relative_manifest_path = format!("{member}/Cargo.toml");
            if let Some(member_manifest) = read_to_string(&manifest_path)? {
                // The consumer's own package name (from its `[package] name = "..."`), not its
                // workspace-relative directory name -- these differ for `apps/cli`, whose package
                // is named `atlas-cli`.
                let consumer_name = member_manifest
                    .lines()
                    .find_map(|line| quoted_field(line.trim(), "name"))
                    .unwrap_or(member);
                kinds_by_consumer.insert(
                    consumer_name.clone(),
                    manifest_dependency_kinds(&member_manifest),
                );
                evidence_by_consumer.insert(consumer_name, relative_manifest_path);
            }
        }
    }

    let mut by_name: BTreeMap<&str, Vec<&LockPackage>> = BTreeMap::new();
    for package in &packages {
        by_name
            .entry(package.name.as_str())
            .or_default()
            .push(package);
    }

    let mut edges = Vec::new();
    let mut dangling_references = Vec::new();
    for package in &packages {
        let consumer_kinds = kinds_by_consumer.get(&package.name);
        let consumer_evidence = evidence_by_consumer
            .get(&package.name)
            .cloned()
            .unwrap_or_else(|| "Cargo.lock".to_owned());
        for dependency_name in &package.dependencies {
            let Some(candidates) = by_name.get(dependency_name.as_str()) else {
                dangling_references.push(format!("{} -> {dependency_name}", package.name));
                continue;
            };
            if candidates.len() > 1 {
                // Multiple resolved versions share this name; disambiguating requires reading the
                // lockfile's `"name version"` array-entry form (see `dependency_array_entry`'s own
                // doc comment), which this parser does not do yet -- reported rather than guessed.
                dangling_references.push(format!(
                    "{} -> {dependency_name} (ambiguous: {} candidates)",
                    package.name,
                    candidates.len()
                ));
                continue;
            }
            let provider_package = candidates[0];
            let source_kind = if provider_package.source.is_some() {
                DependencySourceKind::Registry
            } else {
                DependencySourceKind::WorkspaceMember
            };
            let kind = consumer_kinds.and_then(|declared| {
                declared
                    .iter()
                    .find(|(name, _)| name == dependency_name)
                    .map(|(_, kind)| *kind)
            });
            let evidence_path = if kind.is_some() {
                consumer_evidence.clone()
            } else {
                "Cargo.lock".to_owned()
            };
            edges.push(DependencyEdge {
                consumer: package.name.clone(),
                provider: DependencyIdentity {
                    ecosystem: DependencyEcosystem::Cargo,
                    name: provider_package.name.clone(),
                    version: provider_package.version.clone(),
                    source_kind,
                    source_locator: provider_package.source.clone(),
                    checksum: provider_package.checksum.clone(),
                },
                kind,
                evidence_path,
            });
        }
    }
    edges.sort();
    dangling_references.sort();
    dangling_references.dedup();

    let mut instance_keys: Vec<String> = edges
        .iter()
        .map(|edge| edge.provider.identity_key())
        .collect();
    instance_keys.sort();
    instance_keys.dedup();

    Ok(Some(DependencyClosureReport {
        schema: "atlas.dependency-closure-report.v1".into(),
        ecosystem: DependencyEcosystem::Cargo,
        root: root.to_string_lossy().into_owned(),
        edges_total: edges.len(),
        instances_total: instance_keys.len(),
        edges,
        dangling_references,
    }))
}

#[cfg(test)]
mod tests {
    use super::*;

    // --- 1. Cargo.lock parsing -----------------------------------------------------------------

    const LOCK_FIXTURE: &str = r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "core",
 "syn",
]

[[package]]
name = "core"
version = "0.1.0"

[[package]]
name = "syn"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeef"
dependencies = [
 "unicode-ident",
]

[[package]]
name = "unicode-ident"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cafef00d"
"#;

    #[test]
    fn parses_every_package_block() {
        let packages = parse_cargo_lock(LOCK_FIXTURE);
        assert_eq!(packages.len(), 4);
        let syn = packages.iter().find(|p| p.name == "syn").unwrap();
        assert_eq!(syn.version, "2.0.0");
        assert_eq!(
            syn.source.as_deref(),
            Some("registry+https://github.com/rust-lang/crates.io-index")
        );
        assert_eq!(syn.checksum.as_deref(), Some("deadbeef"));
        assert_eq!(syn.dependencies, vec!["unicode-ident".to_owned()]);
    }

    #[test]
    fn workspace_member_packages_have_no_source() {
        let packages = parse_cargo_lock(LOCK_FIXTURE);
        let core = packages.iter().find(|p| p.name == "core").unwrap();
        assert!(core.source.is_none());
        assert!(core.checksum.is_none());
    }

    #[test]
    fn multi_line_dependency_array_is_parsed() {
        let packages = parse_cargo_lock(LOCK_FIXTURE);
        let adapter = packages.iter().find(|p| p.name == "adapter").unwrap();
        assert_eq!(
            adapter.dependencies,
            vec!["core".to_owned(), "syn".to_owned()]
        );
    }

    #[test]
    fn single_line_dependency_array_is_parsed() {
        let fixture = r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = ["core", "syn"]
"#;
        let packages = parse_cargo_lock(fixture);
        assert_eq!(
            packages[0].dependencies,
            vec!["core".to_owned(), "syn".to_owned()]
        );
    }

    // --- 2. Cargo.toml manifest dependency-table parsing ----------------------------------------

    #[test]
    fn plain_dependencies_table_is_recognized_as_runtime() {
        let manifest = r#"
[package]
name = "adapter"

[dependencies]
atlas_core = { package = "core", path = "../core" }
serde = { workspace = true }
syn = { version = "3.0.6", features = ["full"] }
"#;
        let kinds = manifest_dependency_kinds(manifest);
        assert_eq!(
            kinds,
            vec![
                ("core".to_owned(), DependencyKind::Runtime),
                ("serde".to_owned(), DependencyKind::Runtime),
                ("syn".to_owned(), DependencyKind::Runtime),
            ]
        );
    }

    #[test]
    fn package_rename_resolves_to_the_actual_crate_name() {
        let manifest = r#"
[dependencies]
atlas_core = { package = "core", path = "../core" }
"#;
        let kinds = manifest_dependency_kinds(manifest);
        assert_eq!(kinds, vec![("core".to_owned(), DependencyKind::Runtime)]);
    }

    #[test]
    fn dev_and_build_dependency_tables_are_distinguished_from_plain_dependencies() {
        let manifest = r#"
[dependencies]
serde = "1"

[dev-dependencies]
proptest = "1"

[build-dependencies]
cc = "1"
"#;
        let kinds = manifest_dependency_kinds(manifest);
        assert_eq!(
            kinds,
            vec![
                ("serde".to_owned(), DependencyKind::Runtime),
                ("proptest".to_owned(), DependencyKind::Dev),
                ("cc".to_owned(), DependencyKind::Build),
            ]
        );
    }

    #[test]
    fn dotted_workspace_key_resolves_to_its_bare_crate_name() {
        let manifest = "[dependencies]\nserde.workspace = true\n";
        let kinds = manifest_dependency_kinds(manifest);
        assert_eq!(kinds, vec![("serde".to_owned(), DependencyKind::Runtime)]);
    }

    // --- 3. workspace members array --------------------------------------------------------------

    #[test]
    fn workspace_members_array_is_parsed() {
        let manifest =
            "[workspace]\nmembers = [\"core\", \"runtime\", \"adapter\", \"apps/cli\"]\n";
        assert_eq!(
            workspace_members(manifest),
            vec![
                "core".to_owned(),
                "runtime".to_owned(),
                "adapter".to_owned(),
                "apps/cli".to_owned(),
            ]
        );
    }

    // --- 4. end-to-end census against a synthetic workspace on disk ----------------------------

    fn write(path: &Path, content: &str) {
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, content).unwrap();
    }

    #[test]
    fn end_to_end_census_produces_a_closed_report_with_evidenced_kinds() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-1"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.toml"),
            "[workspace]\nmembers = [\"core\", \"adapter\"]\n",
        );
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "core",
 "syn",
]

[[package]]
name = "core"
version = "0.1.0"

[[package]]
name = "syn"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeef"
"#,
        );
        write(&dir.join("core/Cargo.toml"), "[package]\nname = \"core\"\n");
        write(
            &dir.join("adapter/Cargo.toml"),
            "[package]\nname = \"adapter\"\n\n[dependencies]\natlas_core = { package = \"core\", path = \"../core\" }\nsyn = \"2.0.0\"\n",
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert!(report.is_closed());
        assert_eq!(report.edges_total, 2);
        assert_eq!(report.instances_total, 2);

        let core_edge = report
            .edges
            .iter()
            .find(|edge| edge.provider.name == "core")
            .unwrap();
        assert_eq!(core_edge.consumer, "adapter");
        assert_eq!(core_edge.kind, Some(DependencyKind::Runtime));
        assert_eq!(core_edge.evidence_path, "adapter/Cargo.toml");
        assert_eq!(
            core_edge.provider.source_kind,
            DependencySourceKind::WorkspaceMember
        );

        let syn_edge = report
            .edges
            .iter()
            .find(|edge| edge.provider.name == "syn")
            .unwrap();
        assert_eq!(syn_edge.kind, Some(DependencyKind::Runtime));
        assert_eq!(
            syn_edge.provider.source_kind,
            DependencySourceKind::Registry
        );
        assert_eq!(syn_edge.provider.checksum.as_deref(), Some("deadbeef"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_dangling_dependency_reference_is_reported_not_dropped() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-2"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "adapter"
version = "0.1.0"
dependencies = [
 "ghost-crate",
]
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert!(!report.is_closed());
        assert_eq!(report.edges_total, 0);
        assert_eq!(
            report.dangling_references,
            vec!["adapter -> ghost-crate".to_owned()]
        );

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_root_with_no_cargo_lock_is_not_a_cargo_workspace() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-3"
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        assert!(census_cargo_workspace(&dir).unwrap().is_none());

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_transitive_edge_between_two_external_packages_has_no_guessed_kind() {
        let dir = std::env::temp_dir().join(format!(
            "atlas-dep-census-test-{}",
            std::process::id().to_string() + "-4"
        ));
        let _ = fs::remove_dir_all(&dir);
        write(
            &dir.join("Cargo.lock"),
            r#"
[[package]]
name = "syn"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "deadbeef"
dependencies = [
 "unicode-ident",
]

[[package]]
name = "unicode-ident"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cafef00d"
"#,
        );

        let report = census_cargo_workspace(&dir).unwrap().unwrap();
        assert_eq!(report.edges_total, 1);
        assert_eq!(report.edges[0].kind, None);
        assert_eq!(report.edges[0].evidence_path, "Cargo.lock");

        let _ = fs::remove_dir_all(&dir);
    }

    // --- 5. real self-census: Atlas's own actual Cargo.lock/Cargo.toml files -------------------

    #[test]
    fn real_self_census_of_this_repositorys_own_workspace_finds_no_dangling_references() {
        // Deliberately walks up from this crate's own manifest dir to the real workspace root,
        // so this test exercises the ACTUAL files this repository ships, not only synthetic
        // fixtures -- the "Atlas self-census" case `.atlas/contracts/DEPENDENCY-CENSUS.md`
        // requires.
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("adapter/ has a parent directory");
        let report = census_cargo_workspace(root)
            .expect("reading this repository's own Cargo.lock/Cargo.toml must not fail")
            .expect("this repository's own root has a Cargo.lock");

        assert!(
            report.is_closed(),
            "dangling references in this repository's own real lockfile: {:?}",
            report.dangling_references
        );
        assert!(report.edges_total > 0);

        // Every workspace member's own direct dependency must have an evidenced kind (read from
        // that member's own Cargo.toml), never left as an unevidenced transitive-only edge.
        for member in ["core", "adapter", "runtime", "atlas-cli"] {
            let has_evidenced_edge = report
                .edges
                .iter()
                .any(|edge| edge.consumer == member && edge.kind.is_some());
            assert!(
                has_evidenced_edge,
                "expected at least one evidenced-kind dependency edge for workspace member `{member}`"
            );
        }
    }
}
