// Ynventa declaration (protocol v1). Authoritative and typed: rustc checks it against
// `ynventa::declare::decl`, and every `ynventa` verifier reads it at run time.
// `ynventa` rewrites this file canonically; comments inside the expression are not kept.
&[
    Donor {
        key: "agentir",
        name: "AgentIR",
        origin: "https://github.com/WhitzardAgent/agentir.git",
        license: "file:Apache-2.0",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "construction-pipeline-process",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "trace-ir-process-pattern",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#agentir"],
    },
    Donor {
        key: "arrow",
        name: "Apache Arrow",
        origin: "https://github.com/apache/arrow.git",
        license: "file:.atlas/licenses/donors/arrow/LICENSE.txt file:.atlas/licenses/donors/arrow/NOTICE.txt",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "columnar-memory",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "ipc",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "binary-layout",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "analytics",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#arrow"],
    },
    Donor {
        key: "ast-grep",
        name: "ast-grep",
        origin: "https://github.com/ast-grep/ast-grep.git",
        license: "file:.atlas/licenses/ast-grep/LICENSE",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "structural-search",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "structural-rewrite",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#ast-grep"],
    },
    Donor {
        key: "blake3",
        name: "BLAKE3",
        origin: "https://github.com/BLAKE3-team/BLAKE3.git",
        license: "file:.atlas/licenses/donors/blake3/LICENSE_A2 file:.atlas/licenses/donors/blake3/LICENSE_A2LLVM file:.atlas/licenses/donors/blake3/LICENSE_CC0",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[
            Package {
                ecosystem: Ecosystem::Cargo,
                name: "blake3",
            },
        ],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "hashing",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "content-addressing",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "integrity",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#blake3"],
    },
    Donor {
        key: "buck2",
        name: "Buck2",
        origin: "https://github.com/facebook/buck2.git",
        license: "file:.atlas/licenses/buck2/LICENSE-APACHE file:.atlas/licenses/buck2/LICENSE-MIT file:.atlas/licenses/buck2/NOTICE",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "build-graph",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "target-identity",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "dependency-scheduling",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#buck2"],
    },
    Donor {
        key: "c2rust",
        name: "C2Rust",
        origin: "https://github.com/immunant/c2rust.git",
        license: "file:.atlas/licenses/c2rust/LICENSE",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "source-translation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "migration-ir",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#c2rust"],
    },
    Donor {
        key: "capnproto",
        name: "Cap'n Proto",
        origin: "https://github.com/capnproto/capnproto.git",
        license: "file:MIT",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "binary-encoding",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "canonical-serialization",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "zero-copy-wire-format",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "schema-evolution",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#capnproto"],
    },
    Donor {
        key: "cargo-ed25519-compact",
        name: "ed25519-compact",
        origin: "https://crates.io/crates/ed25519-compact",
        license: "MIT",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[
            Package {
                ecosystem: Ecosystem::Cargo,
                name: "ed25519-compact",
            },
        ],
        source_paths: &[],
        capabilities: &[],
        cutover: None,
        provenance: &[
            "census:adapter/runtime/Cargo.toml",
            "census:apps/cli/Cargo.toml",
            "census:core/Cargo.toml",
            "registry:ed25519-compact-2.6.0/Cargo.toml",
        ],
    },
    Donor {
        key: "cargo-proc-macro2",
        name: "proc-macro2",
        origin: "https://crates.io/crates/proc-macro2",
        license: "MIT OR Apache-2.0",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[
            Package {
                ecosystem: Ecosystem::Cargo,
                name: "proc-macro2",
            },
        ],
        source_paths: &[],
        capabilities: &[],
        cutover: None,
        provenance: &["census:adapter/Cargo.toml", "registry:proc-macro2-1.0.107/Cargo.toml"],
    },
    Donor {
        key: "cargo-quote",
        name: "quote",
        origin: "https://crates.io/crates/quote",
        license: "MIT OR Apache-2.0",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[
            Package {
                ecosystem: Ecosystem::Cargo,
                name: "quote",
            },
        ],
        source_paths: &[],
        capabilities: &[],
        cutover: None,
        provenance: &["census:adapter/Cargo.toml", "registry:quote-1.0.47/Cargo.toml"],
    },
    Donor {
        key: "cargo-serde",
        name: "serde",
        origin: "https://crates.io/crates/serde",
        license: "MIT OR Apache-2.0",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[
            Package {
                ecosystem: Ecosystem::Cargo,
                name: "serde",
            },
        ],
        source_paths: &[],
        capabilities: &[],
        cutover: None,
        provenance: &[
            "census:adapter/Cargo.toml",
            "census:adapter/runtime/Cargo.toml",
            "census:apps/cli/Cargo.toml",
            "census:core/Cargo.toml",
            "registry:serde-1.0.229/Cargo.toml",
        ],
    },
    Donor {
        key: "cargo-serde-json",
        name: "serde_json",
        origin: "https://crates.io/crates/serde_json",
        license: "MIT OR Apache-2.0",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[
            Package {
                ecosystem: Ecosystem::Cargo,
                name: "serde_json",
            },
        ],
        source_paths: &[],
        capabilities: &[],
        cutover: None,
        provenance: &[
            "census:adapter/Cargo.toml",
            "census:adapter/runtime/Cargo.toml",
            "census:apps/cli/Cargo.toml",
            "census:core/Cargo.toml",
            "registry:serde_json-1.0.151/Cargo.toml",
        ],
    },
    Donor {
        key: "cargo-syn",
        name: "syn",
        origin: "https://crates.io/crates/syn",
        license: "MIT OR Apache-2.0",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[
            Package {
                ecosystem: Ecosystem::Cargo,
                name: "syn",
            },
        ],
        source_paths: &[],
        capabilities: &[],
        cutover: None,
        provenance: &["census:adapter/Cargo.toml", "registry:syn-3.0.6/Cargo.toml"],
    },
    Donor {
        key: "cargo-tree-sitter-javascript",
        name: "tree-sitter-javascript",
        origin: "https://crates.io/crates/tree-sitter-javascript",
        license: "MIT",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[
            Package {
                ecosystem: Ecosystem::Cargo,
                name: "tree-sitter-javascript",
            },
        ],
        source_paths: &[],
        capabilities: &[],
        cutover: None,
        provenance: &[
            "census:adapter/Cargo.toml",
            "registry:tree-sitter-javascript-0.23.1/Cargo.toml",
        ],
    },
    Donor {
        key: "cargo-tree-sitter-typescript",
        name: "tree-sitter-typescript",
        origin: "https://crates.io/crates/tree-sitter-typescript",
        license: "MIT",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[
            Package {
                ecosystem: Ecosystem::Cargo,
                name: "tree-sitter-typescript",
            },
        ],
        source_paths: &[],
        capabilities: &[],
        cutover: None,
        provenance: &[
            "census:adapter/Cargo.toml",
            "registry:tree-sitter-typescript-0.23.2/Cargo.toml",
        ],
    },
    Donor {
        key: "clair",
        name: "Clair",
        origin: "https://github.com/quay/clair.git",
        license: "file:.atlas/licenses/donors/clair/LICENSE file:.atlas/licenses/donors/clair/NOTICE",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[],
        source_paths: &[".atlas/temporary/donors/security/clair"],
        capabilities: &[
            Capability {
                key: "security",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "supply-chain",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "vulnerability-intelligence",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#clair"],
    },
    Donor {
        key: "clef",
        name: "Clef Compiler / CCS",
        origin: "https://github.com/FidelityFramework/clef.git",
        license: "file:.atlas/licenses/donors/clef/LICENSE",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "compiler-frontend",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "type-resolution",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "language-service",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#clef"],
    },
    Donor {
        key: "composer",
        name: "Clef / Composer",
        origin: "https://github.com/FidelityFramework/Composer.git",
        license: "file:.atlas/licenses/donors/composer/LICENSE file:.atlas/licenses/donors/composer/Commercial.md file:.atlas/licenses/donors/composer/PATENTS.md",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "program-semantic-graph",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "nanopass-compiler",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "mlir-lowering",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "coeffect-analysis",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "escape-analysis",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "semantic-preservation-verification",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#composer"],
    },
    Donor {
        key: "containers-image",
        name: "containers/image",
        origin: "https://github.com/containers/image.git",
        license: "file:.atlas/licenses/donors/containers-image/LICENSE",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "security",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "trust",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "supply-chain",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "admission-policy",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#containers-image"],
    },
    Donor {
        key: "crubit",
        name: "Crubit",
        origin: "https://github.com/google/crubit.git",
        license: "file:.atlas/licenses/crubit/LICENSE",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "cxx-rust-interop",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "source-translation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#crubit"],
    },
    Donor {
        key: "cytoscape-js",
        name: "Cytoscape.js",
        origin: "https://github.com/cytoscape/cytoscape.js.git",
        license: "file:.atlas/licenses/cytoscape-js/LICENSE file:.atlas/licenses/cytoscape-js/license-update.mjs",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[],
        source_paths: &[".atlas/temporary/donors/cytoscape-js"],
        capabilities: &[
            Capability {
                key: "graph-rendering",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "large-graph-interaction",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#cytoscape-js"],
    },
    Donor {
        key: "datafrog",
        name: "Datafrog",
        origin: "https://github.com/rust-lang/datafrog.git",
        license: "file:.atlas/licenses/datafrog/LICENSE-APACHE file:.atlas/licenses/datafrog/LICENSE-MIT",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "relational-inference",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "fixed-point",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#datafrog"],
    },
    Donor {
        key: "differential-dataflow",
        name: "Differential Dataflow",
        origin: "https://github.com/TimelyDataflow/differential-dataflow.git",
        license: "file:.atlas/licenses/differential-dataflow/LICENSE",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "differential-computation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "incremental-graph-derivation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#differential-dataflow"],
    },
    Donor {
        key: "duumbi",
        name: "DUUMBI",
        origin: "https://github.com/hgahub/duumbi.git",
        license: "file:.atlas/licenses/donors/duumbi/LICENSE",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "graph-native-language",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "cranelift-lowering",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "ai-graph-mutation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "jsonld-surface-representation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "intent-driven-development",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "mcp-graph-tools",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#duumbi"],
    },
    Donor {
        key: "egglog",
        name: "egglog",
        origin: "https://github.com/egraphs-good/egglog.git",
        license: "file:.atlas/licenses/donors/egglog/LICENSE",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "equality-saturation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "e-graph-equivalence-classes",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "datalog-relational-query",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "cost-based-extraction",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "union-find",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "worst-case-optimal-join",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#egglog"],
    },
    Donor {
        key: "elkjs",
        name: "ELK.js",
        origin: "https://github.com/kieler/elkjs.git",
        license: "file:.atlas/licenses/elkjs/LICENSE.md",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[],
        source_paths: &[".atlas/temporary/donors/elkjs"],
        capabilities: &[
            Capability {
                key: "graph-layout",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "automatic-layout",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#elkjs"],
    },
    Donor {
        key: "flatbuffers",
        name: "FlatBuffers",
        origin: "https://github.com/google/flatbuffers.git",
        license: "file:.atlas/licenses/donors/flatbuffers/LICENSE",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "schema",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "serialization",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "zero-copy-binary-format",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "rust-native-reader-writer",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#flatbuffers"],
    },
    Donor {
        key: "glean",
        name: "Glean",
        origin: "https://github.com/facebookincubator/Glean.git",
        license: "file:.atlas/licenses/glean/LICENSE",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "source-facts",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "cross-reference",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "fact-database",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#glean"],
    },
    Donor {
        key: "iris",
        name: "IRIS",
        origin: "https://github.com/boj/iris.git",
        license: "file:.atlas/licenses/donors/iris/LICENSE",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "semantic-graph",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "content-addressing",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "compiler",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "self-evolution",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "formal-verification",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "bytecode-vm",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#iris"],
    },
    Donor {
        key: "joern",
        name: "Joern",
        origin: "https://github.com/joernio/joern.git",
        license: "file:.atlas/licenses/joern/LICENSE",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "code-property-graph",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "data-flow",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "call-graph",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#joern"],
    },
    Donor {
        key: "kani",
        name: "Kani",
        origin: "https://github.com/model-checking/kani.git",
        license: "file:.atlas/licenses/kani/LICENSE-APACHE file:.atlas/licenses/kani/LICENSE-MIT",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "model-checking",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "proof-constraints",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#kani"],
    },
    Donor {
        key: "keycloak",
        name: "Keycloak",
        origin: "https://github.com/keycloak/keycloak.git",
        license: "file:.atlas/licenses/donors/keycloak/LICENSE.txt",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[],
        source_paths: &[".atlas/temporary/donors/security/keycloak"],
        capabilities: &[
            Capability {
                key: "security",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "identity",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "authorization",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "policy",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#keycloak"],
    },
    Donor {
        key: "keylime",
        name: "Keylime",
        origin: "https://github.com/keylime/keylime.git",
        license: "file:.atlas/licenses/donors/keylime/LICENSE",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[],
        source_paths: &[".atlas/temporary/donors/security/keylime"],
        capabilities: &[
            Capability {
                key: "security",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "trust",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "attestation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "integrity",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#keylime"],
    },
    Donor {
        key: "kythe",
        name: "Kythe",
        origin: "https://github.com/kythe/kythe.git",
        license: "file:.atlas/licenses/kythe/LICENSE",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "semantic-cross-reference",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "schema-indexing",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#kythe"],
    },
    Donor {
        key: "ladybird",
        name: "Ladybird",
        origin: "https://github.com/LadybirdBrowser/ladybird.git",
        license: "file:.atlas/licenses/donors/ladybird/LICENSE",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "browser-engine",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "webdriver-automation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "creator-browser-instrument",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#ladybird"],
    },
    Donor {
        key: "llvm-project",
        name: "LLVM Project",
        origin: "https://github.com/llvm/llvm-project.git",
        license: "file:.atlas/licenses/donors/llvm-project/LICENSE.TXT",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "compiler-backend",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "ir",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "optimizer",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "codegen",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "debug-info",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#llvm-project"],
    },
    Donor {
        key: "miri",
        name: "Miri",
        origin: "https://github.com/rust-lang/miri.git",
        license: "file:.atlas/licenses/miri/LICENSE-APACHE file:.atlas/licenses/miri/LICENSE-MIT",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "undefined-behavior-detection",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "rust-execution-semantics",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#miri"],
    },
    Donor {
        key: "mlir",
        name: "MLIR (llvm-project subtree)",
        origin: "https://github.com/llvm/llvm-project.git",
        license: "file:.atlas/licenses/donors/mlir/LICENSE.TXT",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "ir-design",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "dialect-definition",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "bytecode-serialization",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "pattern-rewriting",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "compiler-pass-infrastructure",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "verifier-infrastructure",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#mlir"],
    },
    Donor {
        key: "mold",
        name: "mold",
        origin: "https://github.com/rui314/mold.git",
        license: "file:.atlas/licenses/donors/mold/LICENSE",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "linker",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "elf",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "parallel-linking",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "binary-layout",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#mold"],
    },
    Donor {
        key: "native-coreutils",
        name: "coreutils",
        origin: "https://www.gnu.org/software/coreutils",
        license: "GPL-3.0-or-later",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[
            Package {
                ecosystem: Ecosystem::Native,
                name: "df",
            },
            Package {
                ecosystem: Ecosystem::Native,
                name: "mkfifo",
            },
        ],
        source_paths: &[],
        capabilities: &[],
        cutover: None,
        provenance: &[
            "census:adapter/runtime/src/donor_storage.rs",
            "census:adapter/src/source/mod.rs",
        ],
    },
    Donor {
        key: "native-nodejs",
        name: "nodejs",
        origin: "https://github.com/nodejs/node",
        license: "MIT",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[
            Package {
                ecosystem: Ecosystem::Native,
                name: "node",
            },
        ],
        source_paths: &[],
        capabilities: &[],
        cutover: None,
        provenance: &["census:adapter/src/browser/mod.rs"],
    },
    Donor {
        key: "native-npm",
        name: "npm",
        origin: "https://github.com/npm/cli",
        license: "Artistic-2.0",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[
            Package {
                ecosystem: Ecosystem::Native,
                name: "npm",
            },
        ],
        source_paths: &[],
        capabilities: &[],
        cutover: None,
        provenance: &["census:adapter/src/browser/mod.rs"],
    },
    Donor {
        key: "object",
        name: "object",
        origin: "https://github.com/gimli-rs/object.git",
        license: "file:.atlas/licenses/donors/object/LICENSE-APACHE file:.atlas/licenses/donors/object/LICENSE-MIT",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "object-files",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "elf",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "macho",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "coff",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "debug",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#object"],
    },
    Donor {
        key: "opendesign",
        name: "OpenDesign",
        origin: "https://github.com/vustudio/opendesign.git",
        license: "file:.atlas/licenses/donors/opendesign/LICENSE",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[],
        source_paths: &[".atlas/temporary/donors/opendesign"],
        capabilities: &[
            Capability {
                key: "design-authoring",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "visual-system",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "design-systems",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "prototype-generation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "studio-workspace",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#opendesign"],
    },
    Donor {
        key: "openrewrite",
        name: "OpenRewrite",
        origin: "https://github.com/openrewrite/rewrite.git",
        license: "file:.atlas/licenses/openrewrite/LICENSE",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "semantic-recipes",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "large-scale-migration",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "repeatable-transforms",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#openrewrite"],
    },
    Donor {
        key: "openscap",
        name: "OpenSCAP",
        origin: "https://github.com/OpenSCAP/openscap.git",
        license: "file:.atlas/licenses/donors/openscap/COPYING",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[],
        source_paths: &[".atlas/temporary/donors/security/openscap"],
        capabilities: &[
            Capability {
                key: "security",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "trust",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "compliance",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "policy",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#openscap"],
    },
    Donor {
        key: "podman",
        name: "Podman",
        origin: "https://github.com/containers/podman.git",
        license: "file:.atlas/licenses/donors/podman/LICENSE",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "security",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "trust",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "sandboxing",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "rootless-isolation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#podman"],
    },
    Donor {
        key: "py2many",
        name: "py2many",
        origin: "https://github.com/py2many/py2many.git",
        license: "file:.atlas/licenses/py2many/LICENSE",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[],
        source_paths: &[
            ".atlas/temporary/donors/py2many",
            ".atlas/temporary/donors/py2many/py2many",
        ],
        capabilities: &[
            Capability {
                key: "source-translation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "language-conversion",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#py2many"],
    },
    Donor {
        key: "regalloc2",
        name: "regalloc2",
        origin: "https://github.com/bytecodealliance/regalloc2.git",
        license: "file:.atlas/licenses/donors/regalloc2/LICENSE",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "register-allocation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "compiler-backend",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "machine-ir",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#regalloc2"],
    },
    Donor {
        key: "rkyv",
        name: "rkyv",
        origin: "https://github.com/rkyv/rkyv.git",
        license: "file:MIT",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "binary-encoding",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "zero-copy-archive",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "rust-native-serialization",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "bytes-validation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#rkyv"],
    },
    Donor {
        key: "rust",
        name: "Rust",
        origin: "https://github.com/rust-lang/rust.git",
        license: "file:.atlas/licenses/donors/rust/COPYRIGHT file:.atlas/licenses/donors/rust/LICENSE-APACHE file:.atlas/licenses/donors/rust/license-metadata.json file:.atlas/licenses/donors/rust/LICENSE-MIT",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "compiler",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "borrow-checker",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "codegen",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "standard-toolchain",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#rust"],
    },
    Donor {
        key: "rust-analyzer",
        name: "rust-analyzer",
        origin: "https://github.com/rust-lang/rust-analyzer.git",
        license: "file:.atlas/licenses/rust-analyzer/LICENSE-APACHE file:.atlas/licenses/rust-analyzer/LICENSE-MIT",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "rust-semantics",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "incremental-analysis",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "refactoring",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#rust-analyzer"],
    },
    Donor {
        key: "salsa",
        name: "Salsa",
        origin: "https://github.com/salsa-rs/salsa.git",
        license: "file:.atlas/licenses/salsa/LICENSE-APACHE file:.atlas/licenses/salsa/LICENSE-MIT",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "incremental-queries",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "dependency-invalidation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#salsa"],
    },
    Donor {
        key: "scip",
        name: "SCIP",
        origin: "https://github.com/sourcegraph/scip.git",
        license: "file:.atlas/licenses/scip/LICENSE",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "semantic-index-exchange",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "symbol-identity",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#scip"],
    },
    Donor {
        key: "selinux",
        name: "SELinux",
        origin: "https://github.com/SELinuxProject/selinux.git",
        license: "file:.atlas/licenses/donors/selinux/LICENSE",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[],
        source_paths: &[".atlas/temporary/donors/security/selinux"],
        capabilities: &[
            Capability {
                key: "security",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "trust",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "access-control",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "least-privilege",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#selinux"],
    },
    Donor {
        key: "semgrep",
        name: "Semgrep",
        origin: "https://github.com/semgrep/semgrep.git",
        license: "file:.atlas/licenses/semgrep/LICENSE",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "semantic-search",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "pattern-matching",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "static-analysis",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#semgrep"],
    },
    Donor {
        key: "sigil-lang",
        name: "Sigil",
        origin: "https://github.com/pzalutski-pixel/sigil-lang.git",
        license: "file:.atlas/licenses/donors/sigil-lang/LICENSE",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "graph-native-language",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "content-addressing",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "compiler",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "contract-verification",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#sigil-lang"],
    },
    Donor {
        key: "souffle",
        name: "Souffle",
        origin: "https://github.com/souffle-lang/souffle.git",
        license: "file:.atlas/licenses/souffle/LICENSE",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "datalog",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "static-analysis",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "fixed-point",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#souffle"],
    },
    Donor {
        key: "sourcetrail",
        name: "Sourcetrail",
        origin: "https://github.com/CoatiSoftware/Sourcetrail.git",
        license: "file:.atlas/licenses/sourcetrail/LICENSE.txt",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "source-graph-visualization",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "symbol-navigation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#sourcetrail"],
    },
    Donor {
        key: "tree-sitter",
        name: "Tree-sitter",
        origin: "https://github.com/tree-sitter/tree-sitter.git",
        license: "file:.atlas/licenses/tree-sitter/LICENSE",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[
            Package {
                ecosystem: Ecosystem::Cargo,
                name: "tree-sitter",
            },
        ],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "incremental-parsing",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "syntax-trees",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "query-languages",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#tree-sitter"],
    },
    Donor {
        key: "unadmitted-borg",
        name: "borg",
        origin: "https://github.com/borgbackup/borg.git",
        license: "BSD-3-Clause",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[],
        cutover: None,
        provenance: &[
            "knowledge:DEFINITION .atlas/temporary/donors/borg (ynventa fact list --subject)",
            "legacy:.atlas/roadmap/DONOR-WORKING-SET.toml#retired_checkout:.atlas/temporary/donors/borg",
            "licence:pyproject.toml project.license at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f:.atlas/temporary/donors/borg",
            "origin:.atlas-donor-source.toml at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f:.atlas/temporary/donors/borg",
            "tree:.atlas/temporary/donors/borg at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f (source removed)",
            "verified:https://github.com/borgbackup/borg.git@177d09c9152dcf983f3f3c918bc5ec630cfc7426 compared path by path by git blob id on 2026-10-01",
        ],
    },
    Donor {
        key: "unadmitted-cdc-file-transfer",
        name: "cdc-file-transfer",
        origin: "https://github.com/google/cdc-file-transfer.git",
        license: "Apache-2.0",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[],
        cutover: None,
        provenance: &[
            "knowledge:DEFINITION .atlas/temporary/donors/cdc-file-transfer (ynventa fact list --subject)",
            "legacy:.atlas/roadmap/DONOR-WORKING-SET.toml#retired_checkout:.atlas/temporary/donors/cdc-file-transfer",
            "licence:LICENSE text at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f:.atlas/temporary/donors/cdc-file-transfer",
            "origin:.atlas-donor-source.toml at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f:.atlas/temporary/donors/cdc-file-transfer",
            "tree:.atlas/temporary/donors/cdc-file-transfer at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f (source removed)",
            "verified:https://github.com/google/cdc-file-transfer.git@370023a944d8c81f60463b6659d0de4de99637a7 compared path by path by git blob id on 2026-10-01",
        ],
    },
    Donor {
        key: "unadmitted-fastcdc-rs",
        name: "fastcdc-rs",
        origin: "https://github.com/nlfiedler/fastcdc-rs.git",
        license: "MIT",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[],
        cutover: None,
        provenance: &[
            "knowledge:DEFINITION .atlas/temporary/donors/fastcdc-rs (ynventa fact list --subject)",
            "legacy:.atlas/roadmap/DONOR-WORKING-SET.toml#retired_checkout:.atlas/temporary/donors/fastcdc-rs",
            "licence:Cargo.toml package.license at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f:.atlas/temporary/donors/fastcdc-rs",
            "origin:.atlas-donor-source.toml at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f:.atlas/temporary/donors/fastcdc-rs",
            "tree:.atlas/temporary/donors/fastcdc-rs at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f (source removed)",
            "verified:https://github.com/nlfiedler/fastcdc-rs.git@b025a70229a13d9482c943d27e494c40e84e0892 compared path by path by git blob id on 2026-10-01",
        ],
    },
    Donor {
        key: "unadmitted-git",
        name: "git",
        origin: "https://github.com/git/git.git",
        license: "GPL-2.0-only",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[],
        cutover: None,
        provenance: &[
            "knowledge:DEFINITION .atlas/temporary/donors/git (ynventa fact list --subject)",
            "legacy:.atlas/roadmap/DONOR-WORKING-SET.toml#retired_checkout:.atlas/temporary/donors/git",
            "licence:COPYING text at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f:.atlas/temporary/donors/git",
            "origin:.atlas-donor-source.toml at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f:.atlas/temporary/donors/git",
            "tree:.atlas/temporary/donors/git at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f (source removed)",
            "verified:https://github.com/git/git.git@d38352cd43ab9745686d697872408bc3249a153f compared path by path by git blob id on 2026-10-01",
        ],
    },
    Donor {
        key: "unadmitted-lz4",
        name: "lz4",
        origin: "https://github.com/lz4/lz4.git",
        license: "BSD-2-Clause AND GPL-2.0-or-later",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[],
        cutover: None,
        provenance: &[
            "knowledge:DEFINITION .atlas/temporary/donors/lz4 (ynventa fact list --subject)",
            "legacy:.atlas/roadmap/DONOR-WORKING-SET.toml#retired_checkout:.atlas/temporary/donors/lz4",
            "licence:LICENSE text at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f:.atlas/temporary/donors/lz4",
            "origin:.atlas-donor-source.toml at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f:.atlas/temporary/donors/lz4",
            "tree:.atlas/temporary/donors/lz4 at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f (source removed)",
            "verified:https://github.com/lz4/lz4.git@0774d05537f9762f838f7ab541b7765f1a729cb5 compared path by path by git blob id on 2026-10-01",
        ],
    },
    Donor {
        key: "unadmitted-restic",
        name: "restic",
        origin: "https://github.com/restic/restic.git",
        license: "BSD-2-Clause",
        claimed: DonorState::Registered,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[],
        cutover: None,
        provenance: &[
            "knowledge:DEFINITION .atlas/temporary/donors/restic (ynventa fact list --subject)",
            "legacy:.atlas/roadmap/DONOR-WORKING-SET.toml#retired_checkout:.atlas/temporary/donors/restic",
            "licence:LICENSE text at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f:.atlas/temporary/donors/restic",
            "origin:.atlas-donor-source.toml at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f:.atlas/temporary/donors/restic",
            "tree:.atlas/temporary/donors/restic at 51c41e29a2506b2cf5bb069fbff44f85eaa26e8f (source removed)",
            "verified:https://github.com/restic/restic.git@6adedec6b48ae9ff0ffbc37bd675ccebd02c728f compared path by path by git blob id on 2026-10-01",
        ],
    },
    Donor {
        key: "verus",
        name: "Verus",
        origin: "https://github.com/verus-lang/verus.git",
        license: "file:.atlas/licenses/verus/LICENSE",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "formal-verification",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "proof-oriented-constraints",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#verus"],
    },
    Donor {
        key: "wasm-component-model",
        name: "WebAssembly Component Model",
        origin: "https://github.com/WebAssembly/component-model.git",
        license: "file:.atlas/licenses/donors/wasm-component-model/LICENSE file:.atlas/licenses/donors/wasm-component-model/LICENSE-APACHE",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "interface-definition-language",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "component-boundary",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "canonical-abi",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "type-constructors",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "world-and-interface-composition",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#wasm-component-model"],
    },
    Donor {
        key: "wasm-spec",
        name: "WebAssembly spec",
        origin: "https://github.com/WebAssembly/spec.git",
        license: "file:.atlas/licenses/donors/wasm-spec/LICENSE file:.atlas/licenses/donors/wasm-spec/LICENSE-document file:.atlas/licenses/donors/wasm-spec/LICENSE-interpreter file:.atlas/licenses/donors/wasm-spec/LICENSE-papers file:.atlas/licenses/donors/wasm-spec/LICENSE-test",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "instruction-validation-algorithm",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "stack-machine-type-checking",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "sectioned-binary-format",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "semantic-binary-separation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#wasm-spec"],
    },
    Donor {
        key: "wasm-tools",
        name: "Wasm Tools",
        origin: "https://github.com/bytecodealliance/wasm-tools.git",
        license: "file:.atlas/licenses/donors/wasm-tools/LICENSE-APACHE file:.atlas/licenses/donors/wasm-tools/LICENSE-Apache-2.0_WITH_LLVM-exception file:.atlas/licenses/donors/wasm-tools/LICENSE-MIT",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "wasm",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "component-model",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "binary-tools",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "validation",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#wasm-tools"],
    },
    Donor {
        key: "wasmtime",
        name: "Wasmtime",
        origin: "https://github.com/bytecodealliance/wasmtime.git",
        license: "file:.atlas/licenses/donors/wasmtime/LICENSE",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "wasm-runtime",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "sandboxing",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "cranelift",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "component-model",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#wasmtime"],
    },
    Donor {
        key: "xdsl",
        name: "xDSL",
        origin: "https://github.com/xdslproject/xdsl.git",
        license: "file:.atlas/licenses/donors/xdsl/LICENSE",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "ir-design",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "dialect-definition",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "pattern-rewriting",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "declarative-operation-definition",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "parser-printer-design",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#xdsl"],
    },
    Donor {
        key: "xyflow",
        name: "xyflow",
        origin: "https://github.com/xyflow/xyflow.git",
        license: "file:.atlas/licenses/xyflow/LICENSE",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "node-editor",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "graph-interaction",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#xyflow"],
    },
    Donor {
        key: "zed",
        name: "Zed",
        origin: "https://github.com/zed-industries/zed",
        license: "file:.atlas/licenses/donors/zed/LICENSE-APACHE file:.atlas/licenses/donors/zed/LICENSE-GPL file:.atlas/licenses/donors/zed/ASSET-ICON-LICENSES file:.atlas/licenses/donors/zed/ASSET-THEME-LICENSES",
        claimed: DonorState::Censused,
        exception: Exception::None,
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "ide",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "editor",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "workspace",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "agent-interaction",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "ui-runtime",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#zed"],
    },
    Donor {
        key: "zstd",
        name: "Zstandard",
        origin: "https://github.com/facebook/zstd.git",
        license: "file:.atlas/licenses/donors/zstd/COPYING file:.atlas/licenses/donors/zstd/LICENSE",
        claimed: DonorState::Extinct,
        exception: Exception::Rejected("legacy decision REFERENCE_ONLY: studied, never adopted"),
        packages: &[],
        source_paths: &[],
        capabilities: &[
            Capability {
                key: "compression",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "binary-payloads",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
            Capability {
                key: "compiler-artifact-compression",
                required: true,
                spec: "",
                replacement: None,
                proofs: &[],
            },
        ],
        cutover: None,
        provenance: &["legacy:.atlas/references/donor-corpus.toml#zstd"],
    },
]
