// Ynventa declaration (protocol v1). Authoritative and typed: rustc checks it against
// `ynventa::declare::decl`, and every `ynventa` verifier reads it at run time.
// `ynventa` rewrites this file canonically; comments inside the expression are not kept.
Repository {
    system: "chronica",
    shard: "atlas-studio",
    name: "Atlas-Studio",
    origin: "llgtrn/atlas-studio",
    nodes: &[
        Node {
            key: "ynventa.atlas-studio",
            kind: NodeKind::Ynventa,
            concept: Concept::Subsystem,
            name: "Ynventa protocol subsystem",
            path: ".ynventa",
            canonical_path: ".ynventa",
            lifecycle: NodeLifecycle::Active,
            provides: &[],
            requires: &[],
            reuses: &[],
            inputs: &[],
            outputs: &[],
            lineage: &[],
        },
        Node {
            key: "compiler.adapter",
            kind: NodeKind::Adapter,
            concept: Concept::Subsystem,
            name: "adapter",
            path: "adapter",
            canonical_path: "adapter",
            lifecycle: NodeLifecycle::Active,
            provides: &[],
            requires: &[],
            reuses: &[],
            inputs: &[],
            outputs: &[],
            lineage: &[],
        },
        Node {
            key: "compiler.cli",
            kind: NodeKind::Application,
            concept: Concept::Subsystem,
            name: "apps/cli",
            path: "apps/cli",
            canonical_path: "apps/cli",
            lifecycle: NodeLifecycle::Active,
            provides: &[],
            requires: &[],
            reuses: &[],
            inputs: &[],
            outputs: &[],
            lineage: &[],
        },
        Node {
            key: "compiler.core",
            kind: NodeKind::Kernel,
            concept: Concept::Subsystem,
            name: "core",
            path: "core",
            canonical_path: "core",
            lifecycle: NodeLifecycle::Active,
            provides: &[],
            requires: &[],
            reuses: &[],
            inputs: &[],
            outputs: &[],
            lineage: &[],
        },
        Node {
            key: "compiler.runtime",
            kind: NodeKind::Substrate,
            concept: Concept::Subsystem,
            name: "runtime",
            path: "runtime",
            canonical_path: "substrate/runtime",
            lifecycle: NodeLifecycle::Active,
            provides: &[],
            requires: &[],
            reuses: &[],
            inputs: &[],
            outputs: &[],
            lineage: &[],
        },
        Node {
            key: "compiler.dev",
            kind: NodeKind::Tool,
            concept: Concept::Subsystem,
            name: "tools/dev",
            path: "tools/dev",
            canonical_path: "tools/dev",
            lifecycle: NodeLifecycle::Active,
            provides: &[],
            requires: &[],
            reuses: &[],
            inputs: &[],
            outputs: &[],
            lineage: &[],
        },
        Node {
            key: "compiler.packaging",
            kind: NodeKind::Tool,
            concept: Concept::Subsystem,
            name: "tools/packaging",
            path: "tools/packaging",
            canonical_path: "tools/packaging",
            lifecycle: NodeLifecycle::Active,
            provides: &[],
            requires: &[],
            reuses: &[],
            inputs: &[],
            outputs: &[],
            lineage: &[],
        },
    ],
    edges: &[],
}
