[package]
name = "atlas-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
atlas-model = { path = "../atlas-model" }
atlas-source = { path = "../atlas-source" }
atlas-docs = { path = "../atlas-docs" }
atlas-graph = { path = "../atlas-graph" }
